<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    public function run(): void
    {
        // Tápértékek 100g-ra vonatkoztatva
        $ingredients = [
            ['name' => 'Liszt',              'calories' => 364, 'carbohydrate' => 76.0, 'protein' => 10.0, 'fat' => 1.0],
            ['name' => 'Cukor',              'calories' => 387, 'carbohydrate' => 100.0,'protein' => 0.0,  'fat' => 0.0],
            ['name' => 'Só',                 'calories' => 0,   'carbohydrate' => 0.0,  'protein' => 0.0,  'fat' => 0.0],
            ['name' => 'Tojás',              'calories' => 155, 'carbohydrate' => 1.1,  'protein' => 13.0, 'fat' => 11.0],
            ['name' => 'Tej',                'calories' => 42,  'carbohydrate' => 5.0,  'protein' => 3.4,  'fat' => 1.0],
            ['name' => 'Vaj',                'calories' => 717, 'carbohydrate' => 0.1,  'protein' => 0.9,  'fat' => 81.0],
            ['name' => 'Olaj',               'calories' => 884, 'carbohydrate' => 0.0,  'protein' => 0.0,  'fat' => 100.0],
            ['name' => 'Víz',                'calories' => 0,   'carbohydrate' => 0.0,  'protein' => 0.0,  'fat' => 0.0],
            ['name' => 'Élesztő',            'calories' => 105, 'carbohydrate' => 13.0, 'protein' => 8.0,  'fat' => 1.5],
            ['name' => 'Sütőpor',            'calories' => 53,  'carbohydrate' => 28.0, 'protein' => 0.0,  'fat' => 0.0],
            ['name' => 'Vaníliás cukor',     'calories' => 387, 'carbohydrate' => 97.0, 'protein' => 0.0,  'fat' => 0.0],
            ['name' => 'Csokoládé',          'calories' => 546, 'carbohydrate' => 60.0, 'protein' => 5.0,  'fat' => 31.0],
            ['name' => 'Tejföl',             'calories' => 193, 'carbohydrate' => 3.5,  'protein' => 2.5,  'fat' => 20.0],
            ['name' => 'Tejszín',            'calories' => 340, 'carbohydrate' => 2.8,  'protein' => 2.0,  'fat' => 36.0],
            ['name' => 'Hagyma',             'calories' => 40,  'carbohydrate' => 9.3,  'protein' => 1.1,  'fat' => 0.1],
            ['name' => 'Fokhagyma',          'calories' => 149, 'carbohydrate' => 33.0, 'protein' => 6.4,  'fat' => 0.5],
            ['name' => 'Paprika',            'calories' => 20,  'carbohydrate' => 4.6,  'protein' => 0.9,  'fat' => 0.2],
            ['name' => 'Paradicsom',         'calories' => 18,  'carbohydrate' => 3.9,  'protein' => 0.9,  'fat' => 0.2],
            ['name' => 'Csirkemell',         'calories' => 165, 'carbohydrate' => 0.0,  'protein' => 31.0, 'fat' => 3.6],
            ['name' => 'Darált hús',         'calories' => 250, 'carbohydrate' => 0.0,  'protein' => 17.0, 'fat' => 20.0],
            ['name' => 'Sárgarépa',          'calories' => 41,  'carbohydrate' => 10.0, 'protein' => 0.9,  'fat' => 0.2],
            ['name' => 'Burgonya',           'calories' => 77,  'carbohydrate' => 17.0, 'protein' => 2.0,  'fat' => 0.1],
            ['name' => 'Rizs',               'calories' => 130, 'carbohydrate' => 28.0, 'protein' => 2.7,  'fat' => 0.3],
            ['name' => 'Tészta',             'calories' => 131, 'carbohydrate' => 25.0, 'protein' => 5.0,  'fat' => 1.1],
            ['name' => 'Kenyér',             'calories' => 265, 'carbohydrate' => 49.0, 'protein' => 9.0,  'fat' => 3.2],
            ['name' => 'Sajt',               'calories' => 402, 'carbohydrate' => 1.3,  'protein' => 25.0, 'fat' => 33.0],
            ['name' => 'Sonka',              'calories' => 145, 'carbohydrate' => 1.5,  'protein' => 21.0, 'fat' => 6.0],
            ['name' => 'Bors',               'calories' => 251, 'carbohydrate' => 64.0, 'protein' => 10.0, 'fat' => 3.3],
            ['name' => 'Babérlevél',         'calories' => 313, 'carbohydrate' => 75.0, 'protein' => 7.6,  'fat' => 8.4],
            ['name' => 'Petrezselyem',       'calories' => 36,  'carbohydrate' => 6.3,  'protein' => 3.0,  'fat' => 0.8],
            ['name' => 'Citrom',             'calories' => 29,  'carbohydrate' => 9.3,  'protein' => 1.1,  'fat' => 0.3],
            ['name' => 'Alma',               'calories' => 52,  'carbohydrate' => 14.0, 'protein' => 0.3,  'fat' => 0.2],
            ['name' => 'Banán',              'calories' => 89,  'carbohydrate' => 23.0, 'protein' => 1.1,  'fat' => 0.3],
            ['name' => 'Eper',               'calories' => 32,  'carbohydrate' => 7.7,  'protein' => 0.7,  'fat' => 0.3],
            ['name' => 'Méz',                'calories' => 304, 'carbohydrate' => 82.0, 'protein' => 0.3,  'fat' => 0.0],
            ['name' => 'Cukkini',            'calories' => 17,  'carbohydrate' => 3.1,  'protein' => 1.2,  'fat' => 0.3],
            ['name' => 'Gomba',              'calories' => 22,  'carbohydrate' => 3.3,  'protein' => 3.1,  'fat' => 0.3],
            ['name' => 'Ketchup',            'calories' => 112, 'carbohydrate' => 26.0, 'protein' => 1.2,  'fat' => 0.2],
            ['name' => 'Mustár',             'calories' => 66,  'carbohydrate' => 6.0,  'protein' => 4.0,  'fat' => 3.3],
            ['name' => 'Zsemlemorzsa',       'calories' => 395, 'carbohydrate' => 72.0, 'protein' => 13.0, 'fat' => 5.0],
            ['name' => 'Túró',               'calories' => 98,  'carbohydrate' => 3.4,  'protein' => 11.0, 'fat' => 5.0],
            ['name' => 'Mák',                'calories' => 525, 'carbohydrate' => 28.0, 'protein' => 18.0, 'fat' => 42.0],
            ['name' => 'Kukoricadara',       'calories' => 362, 'carbohydrate' => 77.0, 'protein' => 8.0,  'fat' => 1.5],
            ['name' => 'Szárazbab',          'calories' => 333, 'carbohydrate' => 60.0, 'protein' => 23.0, 'fat' => 1.0],
            ['name' => 'Zöldborsó',          'calories' => 81,  'carbohydrate' => 14.0, 'protein' => 5.0,  'fat' => 0.4],
            ['name' => 'Káposzta',           'calories' => 25,  'carbohydrate' => 5.8,  'protein' => 1.3,  'fat' => 0.1],
            ['name' => 'Savanyú káposzta',   'calories' => 19,  'carbohydrate' => 4.3,  'protein' => 0.9,  'fat' => 0.1],
            ['name' => 'Meggy',              'calories' => 50,  'carbohydrate' => 12.0, 'protein' => 1.0,  'fat' => 0.3],
            ['name' => 'Dió',                'calories' => 654, 'carbohydrate' => 14.0, 'protein' => 15.0, 'fat' => 65.0],
            ['name' => 'Spenót',             'calories' => 23,  'carbohydrate' => 3.6,  'protein' => 2.9,  'fat' => 0.4],
            ['name' => 'Sárgaborsó',         'calories' => 341, 'carbohydrate' => 60.0, 'protein' => 25.0, 'fat' => 1.2],
            ['name' => 'Málna',              'calories' => 52,  'carbohydrate' => 12.0, 'protein' => 1.2,  'fat' => 0.7],
            // Húsok, halak
            ['name' => 'Sertéshús',          'calories' => 242, 'carbohydrate' => 0.0,  'protein' => 27.0, 'fat' => 14.0],
            ['name' => 'Marhahús',           'calories' => 250, 'carbohydrate' => 0.0,  'protein' => 26.0, 'fat' => 15.0],
            ['name' => 'Kolbász',            'calories' => 301, 'carbohydrate' => 1.0,  'protein' => 15.0, 'fat' => 26.0],
            ['name' => 'Füstölt csülök',     'calories' => 280, 'carbohydrate' => 0.0,  'protein' => 18.0, 'fat' => 23.0],
            ['name' => 'Füstölt tarja',      'calories' => 250, 'carbohydrate' => 0.5,  'protein' => 20.0, 'fat' => 18.0],
            ['name' => 'Szalonna',           'calories' => 541, 'carbohydrate' => 0.7,  'protein' => 12.0, 'fat' => 55.0],
            ['name' => 'Virsli',             'calories' => 260, 'carbohydrate' => 2.0,  'protein' => 12.0, 'fat' => 22.0],
            ['name' => 'Ponty',              'calories' => 127, 'carbohydrate' => 0.0,  'protein' => 18.0, 'fat' => 5.6],
            ['name' => 'Harcsa',             'calories' => 116, 'carbohydrate' => 0.0,  'protein' => 17.0, 'fat' => 4.8],
            ['name' => 'Keszeg',             'calories' => 105, 'carbohydrate' => 0.0,  'protein' => 18.0, 'fat' => 3.0],
            ['name' => 'Csirkecomb',         'calories' => 184, 'carbohydrate' => 0.0,  'protein' => 27.0, 'fat' => 8.0],
            // Tésztafélék
            ['name' => 'Spagetti',           'calories' => 158, 'carbohydrate' => 31.0, 'protein' => 5.8,  'fat' => 0.9],
            ['name' => 'Nokedli',            'calories' => 140, 'carbohydrate' => 26.0, 'protein' => 5.0,  'fat' => 1.5],
            ['name' => 'Csipetke',           'calories' => 140, 'carbohydrate' => 26.0, 'protein' => 5.0,  'fat' => 1.5],
            ['name' => 'Tarhonya',           'calories' => 145, 'carbohydrate' => 28.0, 'protein' => 5.0,  'fat' => 1.0],
            ['name' => 'Makaróni',           'calories' => 157, 'carbohydrate' => 30.0, 'protein' => 5.8,  'fat' => 1.0],
            ['name' => 'Lasagne tészta',     'calories' => 150, 'carbohydrate' => 29.0, 'protein' => 5.5,  'fat' => 1.0],
            ['name' => 'Csigatészta',        'calories' => 150, 'carbohydrate' => 29.0, 'protein' => 5.5,  'fat' => 1.0],
            ['name' => 'Penne',              'calories' => 157, 'carbohydrate' => 30.0, 'protein' => 5.8,  'fat' => 1.0],
            ['name' => 'Tortilla',           'calories' => 300, 'carbohydrate' => 50.0, 'protein' => 8.0,  'fat' => 7.0],
            ['name' => 'Pita',               'calories' => 275, 'carbohydrate' => 55.0, 'protein' => 9.0,  'fat' => 1.2],
            ['name' => 'Kifli',              'calories' => 280, 'carbohydrate' => 52.0, 'protein' => 8.0,  'fat' => 4.0],
            // Zöldségek, gyümölcsök
            ['name' => 'Karfiol',            'calories' => 25,  'carbohydrate' => 5.0,  'protein' => 1.9,  'fat' => 0.3],
            ['name' => 'Brokkoli',           'calories' => 34,  'carbohydrate' => 7.0,  'protein' => 2.8,  'fat' => 0.4],
            ['name' => 'Cékla',              'calories' => 43,  'carbohydrate' => 10.0, 'protein' => 1.6,  'fat' => 0.2],
            ['name' => 'Sütőtök',            'calories' => 26,  'carbohydrate' => 6.5,  'protein' => 1.0,  'fat' => 0.1],
            ['name' => 'Zeller',             'calories' => 16,  'carbohydrate' => 3.0,  'protein' => 0.7,  'fat' => 0.2],
            ['name' => 'Uborka',             'calories' => 15,  'carbohydrate' => 3.6,  'protein' => 0.7,  'fat' => 0.1],
            ['name' => 'Saláta',             'calories' => 15,  'carbohydrate' => 2.9,  'protein' => 1.4,  'fat' => 0.2],
            ['name' => 'Paradicsomszósz',    'calories' => 38,  'carbohydrate' => 7.0,  'protein' => 1.5,  'fat' => 0.3],
            ['name' => 'Olívabogyó',         'calories' => 115, 'carbohydrate' => 6.3,  'protein' => 0.8,  'fat' => 10.7],
            ['name' => 'Baracklekvár',       'calories' => 250, 'carbohydrate' => 60.0, 'protein' => 0.5,  'fat' => 0.1],
            // Sajtok
            ['name' => 'Parmezán',           'calories' => 431, 'carbohydrate' => 4.1,  'protein' => 38.0, 'fat' => 29.0],
            ['name' => 'Feta sajt',          'calories' => 264, 'carbohydrate' => 4.1,  'protein' => 14.0, 'fat' => 21.0],
            ['name' => 'Ricotta',            'calories' => 174, 'carbohydrate' => 3.0,  'protein' => 11.0, 'fat' => 13.0],
            ['name' => 'Mascarpone',         'calories' => 429, 'carbohydrate' => 2.3,  'protein' => 4.9,  'fat' => 44.0],
            // Fűszerek, ízesítők
            ['name' => 'Pirospaprika őrlemény','calories' => 282,'carbohydrate' => 54.0, 'protein' => 14.0, 'fat' => 13.0],
            ['name' => 'Fahéj',              'calories' => 247, 'carbohydrate' => 81.0, 'protein' => 4.0,  'fat' => 1.2],
            ['name' => 'Kakaópor',           'calories' => 228, 'carbohydrate' => 58.0, 'protein' => 20.0, 'fat' => 14.0],
            ['name' => 'Vanília',            'calories' => 288, 'carbohydrate' => 13.0, 'protein' => 0.1,  'fat' => 0.1],
            ['name' => 'Tárkony',            'calories' => 295, 'carbohydrate' => 50.0, 'protein' => 23.0, 'fat' => 7.0],
            ['name' => 'Bazsalikom',         'calories' => 23,  'carbohydrate' => 2.7,  'protein' => 3.2,  'fat' => 0.6],
            ['name' => 'Chili',              'calories' => 40,  'carbohydrate' => 8.8,  'protein' => 1.9,  'fat' => 0.4],
            ['name' => 'Curry por',          'calories' => 325, 'carbohydrate' => 56.0, 'protein' => 14.0, 'fat' => 14.0],
            ['name' => 'Ecet',               'calories' => 21,  'carbohydrate' => 0.9,  'protein' => 0.0,  'fat' => 0.0],
            ['name' => 'Majonéz',            'calories' => 680, 'carbohydrate' => 0.6,  'protein' => 1.0,  'fat' => 75.0],
            // Egyéb
            ['name' => 'Keményítő',          'calories' => 381, 'carbohydrate' => 91.0, 'protein' => 0.3,  'fat' => 0.1],
            ['name' => 'Zabpehely',          'calories' => 389, 'carbohydrate' => 66.0, 'protein' => 17.0, 'fat' => 6.9],
            ['name' => 'Kávé',               'calories' => 2,   'carbohydrate' => 0.0,  'protein' => 0.1,  'fat' => 0.0],
            ['name' => 'Tökmag',             'calories' => 559, 'carbohydrate' => 11.0, 'protein' => 30.0, 'fat' => 49.0],
            ['name' => 'Zsír',               'calories' => 896, 'carbohydrate' => 0.0,  'protein' => 0.0,  'fat' => 99.0],
        ];

        DB::table('ingredient')->insert($ingredients);
    }
}