<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StepSeeder extends Seeder
{
    public function run(): void
    {
        $recipeSteps = [
            1  => ['A marhahúst megmossuk és kockákra vágjuk.', 'A hagymát apróra vágjuk, olajon üvegesre pirítjuk.', 'Pirospaprikával megszórjuk, hozzáadjuk a húst, átforgatjuk.', 'Felöntjük vízzel, sózzuk, borsozzuk, babérlevelet adunk hozzá.', 'Hozzáadjuk a felkockázott burgonyát, sárgarépát és paprikát.', 'Lassú tűzön puhára főzzük, tálaláskor friss kenyérrel kínáljuk.'],
            2  => ['A csirkemellet megmossuk, feldaraboljuk.', 'A hagymát apróra vágjuk, olajon megpirítjuk.', 'Pirospaprikával megszórjuk, hozzáadjuk a csirkét és átforgatjuk.', 'Felöntjük vízzel, hozzáadjuk a felszeletelt paprikát és paradicsomot.', 'Sózzuk, borsozzuk, lassú tűzön puhára pároljuk.', 'Tejföllel tálaljuk, nokedli körettel.'],
            3  => ['A tésztát bő, sós vízben kifőzzük, leszűrjük.', 'A szalonnát apró kockákra vágjuk, serpenyőben ropogósra sütjük.', 'A túrót áttörjük, tejföllel és kevés cukorral krémesre keverjük.', 'A leszűrt tésztát összekeverjük a túrós krémmel.', 'Tányérra halmozzuk, a tetejére szórjuk a ropogós szalonnapörcöt.', 'Azonnal tálaljuk, amíg a tészta forró.'],
            4  => ['A burgonyát héjában megfőzzük, majd meghámozzuk és karikákra vágjuk.', 'A tojásokat keményre főzzük, meghámozzuk és felszeleteljük.', 'A kolbászt vékony karikákra vágjuk.', 'Egy kivajazott tepsibe rétegezzük: burgonya, tojás, kolbász, tejföl, só.', 'A rétegezést addig ismételjük, amíg a hozzávalók el nem fogynak.', 'Előmelegített sütőben 180°C-on aranybarnára sütjük.'],
            5  => ['A halakat megtisztítjuk, a pontyot, harcsát és keszeget feldaraboljuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Pirospaprikával megszórjuk, majd felöntjük vízzel.', 'Beletesszük a halfejeket és farkokat, felforraljuk.', 'Amikor az alaplé elkészült, beletesszük a halszeleteket.', 'Lassú tűzön készre főzzük, tésztával tálaljuk.'],
            6  => ['Az élesztőt langyos tejben egy kevés cukorral felfuttatjuk.', 'A lisztet egy tálba szitáljuk, hozzáadjuk a felfutott élesztőt és sót.', 'Alaposan kidagasztjuk a tésztát, majd letakarva a duplájára kelesztjük.', 'A tésztát kinyújtjuk, tetszőleges formákra szaggatjuk.', 'Bő, forró olajban mindkét oldalát aranybarnára sütjük.', 'Tejföllel megkenjük, reszelt sajttal megszórva tálaljuk.'],
            7  => ['Lisztből, tojásból, tejből, cukorból és egy csipet sóból palacsintatésztát keverünk.', 'A tésztát simára keverjük, majd 15 percig pihentetjük.', 'Egy serpenyőben kevés olajat forrósítunk, majd vékonyan belemerünk a tésztából.', 'Mindkét oldalát aranybarnára sütjük, majd megtöltjük ízlés szerint.', 'Kakaóval, lekvárral vagy túróval töltve, feltekerve tálaljuk.'],
            8  => ['A sertéshúst megmossuk, felkockázzuk.', 'A hagymát apróra vágjuk, olajon megpirítjuk.', 'Pirospaprikával megszórjuk, hozzáadjuk a húst, átpirítjuk.', 'Hozzáadjuk a savanyú káposztát, elkeverjük.', 'Felöntjük vízzel, sózzuk, borsozzuk, babérlevelet adunk hozzá.', 'Lassú tűzön puhára főzzük, tejföllel tálaljuk.'],
            9  => ['A csirkemellet megmossuk, feldaraboljuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Pirospaprikával megszórjuk, hozzáadjuk a csirkét és átforgatjuk.', 'Felöntjük vízzel, sózzuk, borsozzuk.', 'Amikor a hús megpuhult, tejfölös habarással sűrítjük.', 'Összeforraljuk, nokedlivel tálaljuk.'],
            10 => ['Lisztből, vajból, cukorból, tojásból omlós tésztát gyúrunk, két részre osztjuk.', 'A tészta egyik felét kinyújtjuk és kivajazott tepsibe tesszük.', 'A meggyet cukorral és fahéjjal összekeverjük, a tésztára egyenletesen elosztjuk.', 'A másik tésztalapot is kinyújtjuk, csíkokra vágjuk, rácsos mintát készítünk a tetejére.', 'Előmelegített sütőben 180°C-on aranybarnára sütjük.', 'Porcukorral meghintve, kihűlés után szeleteljük.'],
            11 => ['A hagymát és fokhagymát apróra vágjuk, olajon megpirítjuk.', 'Hozzáadjuk a darált húst, és fehéredésig pirítjuk.', 'Hozzáadjuk a felkockázott paradicsomot, reszelt sárgarépát és apróra vágott zellert.', 'Felöntjük paradicsomszósszal, sózzuk, borsozzuk, bazsalikommal fűszerezzük.', 'Lassú tűzön legalább 1 órán át főzzük a mártást.', 'A spagettit bő sós vízben kifőzzük, leszűrjük, a szósszal tálaljuk.'],
            12 => ['A csirkemellet sózzuk, borsozzuk, kevés olajjal megkenjük.', 'Grillserpenyőben vagy grillen mindkét oldalát megsütjük.', 'A salátát megmossuk, leveleit darabokra tépkedjük.', 'A paradicsomot cikkekre vágjuk, a salátához adjuk.', 'A megsült csirkét felszeleteljük, a salátára fektetjük.', 'Citromlével meglocsoljuk, citromkarikákkal díszítve tálaljuk.'],
            13 => ['A paprikák tetejét levágjuk, magházukat és ereit eltávolítjuk.', 'A darált húst összekeverjük a rizzsel, apróra vágott hagymával, sóval, borssal.', 'A paprikákat szorosan megtöltjük a húsos-rizses töltelékkel.', 'Egy lábasba állítjuk a megtöltött paprikákat, felöntjük paradicsomszósszal.', 'Lassú tűzön, lefedve kb. 40-50 percig főzzük.', 'Főtt burgonyával vagy friss kenyérrel tálaljuk.'],
            14 => ['A hagymát apróra vágjuk, vajon megdinszteljük.', 'Hozzáadjuk a zöldborsót, felöntjük vízzel és tejjel.', 'Sózzuk, borsozzuk, közepes lángon puhára főzzük.', 'Tejszínnel dúsítjuk, botmixerrel krémesre turmixoljuk.', 'A kenyeret kockákra vágjuk, serpenyőben aranybarnára pirítjuk.', 'A levest tányérokba merjük, pirított kenyérkockákkal megszórva tálaljuk.'],
            15 => ['A sajtot kb. 1 cm vastag szeletekre vágjuk.', 'Először lisztbe, majd felvert tojásba, végül zsemlemorzsába forgatjuk.', 'A panírozást megismételjük, hogy vastagabb, ropogósabb bundát kapjunk.', 'Bő, forró olajban aranybarnára sütjük mindkét oldalát.', 'Papírtörlőre szedjük, hogy a felesleges olajat lecsöpögtessük.', 'Hasábburgonyával és tartármártással tálaljuk.'],
            16 => ['Lisztből, vajból, cukorból, tojásból tésztát gyúrunk, három egyenlő részre osztjuk.', 'A tésztákat vékony lapokra nyújtjuk, tepsi hátán világosra sütjük.', 'A diót ledaráljuk, cukorral összekeverjük.', 'Az első lapot megkenjük baracklekvárral, megszórjuk diós cukorral, majd jön a következő lap.', 'A rétegezést megismételjük, a tetejét csokoládébevonattal vonjuk be.', 'Hűtőben megdermesztjük, majd szeletelve tálaljuk.'],
            17 => ['A fokhagymagerezdeket meghámozzuk, vékonyan felszeleteljük.', 'Egy lábasban vajat olvasztunk, a fokhagymát lassan, alacsony lángon üvegesre pároljuk.', 'Felöntjük vízzel és tejjel, sózzuk, borsozzuk, felforraljuk.', 'Tejszínnel dúsítjuk, botmixerrel teljesen krémesre turmixoljuk.', 'A kenyeret kockákra vágjuk, serpenyőben aranybarnára pirítjuk.', 'A levest tányérokba merjük, pirított kenyérkockákkal és reszelt sajttal tálaljuk.'],
            18 => ['A marhahúst megmossuk, kisebb kockákra vágjuk.', 'A hagymát apróra vágjuk, zsíron aranybarnára pirítjuk.', 'Pirospaprikával megszórjuk, gyorsan elkeverjük, majd hozzáadjuk a húst.', 'Addig pirítjuk, amíg a hús kifehéredik, majd felöntjük vízzel.', 'Sózzuk, borsozzuk, babérlevelet adunk hozzá, lassú tűzön 1,5-2 órán át főzzük.', 'Amikor a hús megpuhult, csipetkével tálaljuk.'],
            19 => ['Tojásból, lisztből, cukorból 6-8 vékony piskótalapot sütünk (laponként kb. 5 perc).', 'A vajkrémet vajból, cukorból, tojásból gőz felett kikeverjük, majd kihűtjük.', 'A kihűlt piskótalapokat egyenletesen megkenjük a vajkrémmel, egymásra rétegezzük.', 'A legfelső lapra is kenünk egy vékony réteg krémet.', 'Cukrot karamellizálunk, a torta tetejére öntjük, késsel elsimítjuk.', 'Hűtőben pihentetjük, majd a karamell megdermedése után szeleteljük.'],
            20 => ['A káposztát megmossuk, vékony csíkokra vágjuk vagy legyaluljuk.', 'Egy serpenyőben zsírt forrósítunk, hozzáadjuk a káposztát.', 'Közepes lángon, gyakran kevergetve aranybarnára pirítjuk a káposztát, sózzuk, borsozzuk.', 'A tésztát bő, sós vízben kifőzzük, leszűrjük.', 'A leszűrt tésztát összekeverjük a pirított káposztával.', 'Azonnal tálaljuk, ízlés szerint porcukorral meghinthetjük.'],
            21 => ['A sertésbordát kiklopfoljuk, sózzuk, borsozzuk.', 'Lisztbe, majd felvert tojásba, végül zsemlemorzsába forgatjuk.', 'Bő, forró olajban mindkét oldalát aranybarnára sütjük.', 'Papírtörlőre szedjük, hogy a felesleges olajat lecsöpögtessük.', 'Citromkarikákkal és sült burgonyával tálaljuk.'],
            22 => ['A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a felkockázott paradicsomot, felöntjük vízzel és tejjel.', 'Sózzuk, egy kevés cukorral ízesítjük, bazsalikomot adunk hozzá.', 'Puhára főzzük, majd botmixerrel simára turmixoljuk.', 'Tejföllel dúsítjuk, összeforraljuk.', 'Pirított kenyérkockákkal megszórva tálaljuk.'],
            23 => ['A savanyú káposztát ha szükséges, átmossuk, lecsöpögtetjük.', 'A darált húst összekeverjük a rizzsel, apróra vágott hagymával, sóval, borssal.', 'A káposztalevelekbe göngyöljük a tölteléket, szorosan feltekerjük.', 'Egy nagy lábasba rétegezzük: káposzta, töltelékek, füstölt tarja, kolbász.', 'Felöntjük vízzel, hogy ellepje, lassú tűzön kb. 2 órán át főzzük.', 'Tejföllel meglocsolva, friss kenyérrel tálaljuk.'],
            24 => ['A kifliket karikákra vágjuk, egy tálba tesszük.', 'A tejet meglangyosítjuk, vaníliával ízesítjük, a kiflire öntjük.', 'Állni hagyjuk, amíg a kifli megpuhul és magába szívja a tejet.', 'A mákot cukorral összekeverjük, a megpuhult kiflire szórjuk.', 'Vaníliasodót készítünk (tej, cukor, vanília, tojássárgája).', 'A mákos gubát tányérokra adagoljuk, gazdagon leöntjük a vaníliasodóval.'],
            25 => ['A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a zöldborsót, felöntjük vízzel, sózzuk.', 'Közepes lángon puhára főzzük a borsót.', 'Lisztből és olajból világos rántást készítünk, hideg vízzel felöntjük, simára keverjük.', 'A rántást a borsóhoz adjuk, összeforraljuk.', 'A virslit forró vízben átmelegítjük, a főzelékkel tálaljuk.'],
            26 => ['A csirkemellet megmossuk, feldaraboljuk.', 'A hagymát apróra vágjuk, zsíron aranybarnára pirítjuk.', 'Pirospaprikával megszórjuk, gyorsan elkeverjük, hozzáadjuk a csirkét.', 'Felöntjük vízzel, sózzuk, borsozzuk, hozzáadjuk a felszeletelt paprikát.', 'Puhára pároljuk, majd tejfölös habarással sűrítjük.', 'Összeforraljuk, galuskával tálaljuk.'],
            27 => ['Lisztből, vízből, olajból, csipet sóból rétestésztát készítünk, cipóba formázzuk.', 'A cipót letakarva pihentetjük, majd vékonyra nyújtjuk.', 'Az almát meghámozzuk, lereszeljük, cukorral, fahéjjal és darált dióval összekeverjük.', 'A tölteléket a tésztára egyenletesen elosztjuk, majd óvatosan feltekerjük.', 'Kivajazott tepsibe fektetjük, a tetejét megkenjük olvasztott vajjal.', 'Előmelegített sütőben 180°C-on aranybarnára sütjük, porcukorral meghintjük.'],
            28 => ['A hagymát és fokhagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a spenótot (ha fagyasztott, akkor felengedve), sózzuk, borsozzuk.', 'Közepes lángon, gyakran kevergetve megpároljuk.', 'Tejszínnel és tejföllel dúsítjuk, liszttel megszórva besűrítjük.', 'Összeforraljuk, hogy a liszt csomómentesen elkeveredjen.', 'Főtt tojással, szeletelve tálaljuk.'],
            29 => ['A sertésbordát kiklopfoljuk, sózzuk, borsozzuk.', 'Kevés olajon elősütjük a hússzeleteket mindkét oldalukon, majd tepsibe rakjuk.', 'A gombát felszeleteljük, a hagymával együtt olajon megpároljuk.', 'Tejföllel és tejszínnel összekeverjük a gombás ragu, a húsra öntjük.', 'Előmelegített sütőben 180°C-on kb. 20-25 percig sütjük.', 'Rizzsel vagy tésztával tálaljuk.'],
            30 => ['A burgonyát meghámozzuk, felkockázzuk.', 'Sós vízben puhára főzzük.', 'Lisztből és olajból világos rántást készítünk, hideg vízzel felöntjük, simára keverjük.', 'A rántást a burgonyához adjuk, összeforraljuk.', 'Frissen aprított petrezselyemmel megszórva tálaljuk.'],
            31 => ['A gombát megtisztítjuk, felszeleteljük.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a gombát, pirospaprikával megszórjuk, átforgatjuk.', 'Sózzuk, borsozzuk, hozzáadjuk a felszeletelt paprikát, felöntjük kevés vízzel.', 'Puhára pároljuk, majd tejföllel dúsítjuk, összeforraljuk.', 'Galuskával vagy nokedlivel tálaljuk.'],
            32 => ['A túrót áttörjük, hogy ne legyen csomós.', 'Összekeverjük a tojással, cukorral, liszttel és egy csipet sóval.', 'Nedves kézzel diónyi gombócokat formázunk a masszából.', 'Forró, enyhén sós vízben kifőzzük a gombócokat (amikor feljönnek a víz felszínére, még 3-4 percig főzzük).', 'Szűrőkanállal kiszedjük, lecsepegtetjük, majd zsemlemorzsába forgatjuk.', 'Tejföllel és porcukorral megszórva tálaljuk.'],
            33 => ['A marhahúst hideg vízben feltesszük főni.', 'Amikor felforrt, a habot gondosan leszedjük a tetejéről.', 'Hozzáadjuk a megtisztított, nagyobb darabokra vágott zöldségeket (sárgarépa, burgonya, hagyma).', 'Sózzuk, egész borsot és babérlevelet adunk hozzá.', 'Lassú tűzön 2-3 órán át gyöngyözve főzzük.', 'A levest leszűrjük, a húst és zöldségeket felszeleteljük, csigatésztával tálaljuk.'],
            34 => ['A palacsintatésztát összekeverjük (liszt, tojás, tej, cukor), majd vékony palacsintákat sütünk.', 'A darált húst apróra vágott hagymával, sóval, borssal olajon megpároljuk.', 'Egy kivajazott tepsibe egy réteg palacsintát fektetünk.', 'Megkenjük a húsos raguval, tejföllel meglocsoljuk, sajttal megszórjuk.', 'A rétegezést addig ismételjük, amíg a hozzávalók el nem fogynak, a tetejére sajt kerüljön.', 'Előmelegített sütőben 180°C-on kb. 20 perc alatt összesütjük.'],
            35 => ['A darált húst összekeverjük a tojással, apróra vágott hagymával, sóval, borssal és zsemlemorzsával.', 'Alaposan összedolgozzuk a masszát, majd vizes kézzel gombócokat formázunk.', 'Sütőpapírral bélelt tepsire sorakoztatjuk a fasírtgombócokat, kevés olajjal megkenjük.', 'Előmelegített sütőben 180°C-on kb. 25-30 perc alatt aranybarnára sütjük.', 'A burgonyát meghámozzuk, felkockázzuk, sós vízben puhára főzzük.', 'A burgonyát összetörjük, vajjal és tejjel krémesre keverjük, a fasírttal tálaljuk.'],
            36 => ['A karfiolt rózsáira szedjük, alaposan megmossuk.', 'Sós vízben puhára főzzük a karfiolt.', 'Hozzáadjuk a tejet és a tejszínt, összeforraljuk.', 'Reszelt sajtot keverünk bele, amíg elolvad.', 'Botmixerrel teljesen krémesre turmixoljuk.', 'Tányérokba merjük, kevés reszelt sajttal és pirított kenyérkockákkal tálaljuk.'],
            37 => ['A tojásokat keményre főzzük (kb. 10 perc), majd hideg vízben lehűtjük.', 'Meghámozzuk, félbevágjuk, a sárgájukat óvatosan kikaparjuk egy tálba.', 'A tojássárgáját villával összetörjük, mustárral, majonézzel, sóval, borssal simára keverjük.', 'A krémet habzsákba töltjük, és visszatöltjük a tojásfehérjékbe.', 'Frissen aprított petrezselyemmel megszórva tálaljuk.'],
            38 => ['A szárazbabot előző este hideg vízben beáztatjuk.', 'Másnap a babot leszűrjük, friss vízben feltesszük főni.', 'Hozzáadjuk a füstölt tarját, az apróra vágott hagymát, olajat.', 'Sózzuk, borsozzuk, babérlevelet adunk hozzá.', 'Lassú tűzön több órán át főzzük, amíg a bab és a hús is megpuhul.', 'Főtt tojással és friss kenyérrel tálaljuk.'],
            39 => ['A gyümölcsöket (alma, banán, eper stb.) megtisztítjuk, felkockázzuk.', 'Vízben cukorral és fahéjjal megfőzzük a gyümölcsöket.', 'Tejszínnel dúsítjuk, összeforraljuk.', 'Botmixerrel vagy hagyományosan simára turmixoljuk / áttörjük.', 'Lehűtjük, hidegre hűtve tálaljuk.'],
            40 => ['A kukoricadarát sós vízben, folyamatosan kevergetve sűrűre főzzük.', 'Amikor besűrűsödött és elválik a lábas falától, tányérra borítjuk.', 'Tejföllel gazdagon megkenjük a tetejét.', 'Reszelt sajttal bőségesen megszórjuk.', 'Azonnal, forrón tálaljuk.'],
            41 => ['A sertésszeleteket kiklopfoljuk, sózzuk, borsozzuk.', 'Serpenyőben kevés olajon mindkét oldalukat elősütjük.', 'A hússzeleteket tepsibe fektetjük, paradicsomszeleteket teszünk rájuk.', 'Bőségesen megszórjuk reszelt sajttal.', 'Előmelegített sütőben addig sütjük, amíg a sajt ráolvad és aranybarnára pirul.', 'Rizzsel vagy sült burgonyával tálaljuk.'],
            42 => ['A szárazbabot előző este hideg vízben beáztatjuk.', 'Másnap a babot leszűrjük, friss vízben feltesszük főni a füstölt csülökkel együtt.', 'Hozzáadjuk az apróra vágott hagymát, fokhagymát, pirospaprikát.', 'Sózzuk, borsozzuk, lassú tűzön főzzük.', 'Amikor a bab és a csülök megpuhult, a csülköt kivesszük, feldaraboljuk és visszatesszük.', 'Friss kenyérrel és csípős paprikával tálaljuk.'],
            43 => ['Az élesztőt langyos tejben egy kevés cukorral felfuttatjuk.', 'Lisztből, vajból, cukorból, tojásból és a felfutott élesztőből tésztát dagasztunk, kelni hagyjuk.', 'A megkelt tésztát kinyújtjuk téglalap alakúra.', 'Megszórjuk kakaópor és cukor keverékével, majd szorosan feltekerjük.', 'Felszeleteljük, sütőpapírral bélelt tepsibe rakjuk, újra kelesztjük.', 'Előmelegített sütőben 180°C-on aranybarnára sütjük.'],
            44 => ['A burgonyát meghámozzuk, felkockázzuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a burgonyát, felöntjük vízzel.', 'Sózzuk, borsozzuk, ecettel savanyítjuk, hozzáadjuk a füstölt tarját.', 'Amikor a burgonya megpuhult, a füstölt tarját kivesszük, feldaraboljuk, visszatesszük.', 'A végén hozzáadjuk a felkarikázott kolbászt, összeforraljuk és tálaljuk.'],
            45 => ['A csirkemellet kiklopfoljuk, sózzuk, borsozzuk.', 'Lisztbe, majd felvert tojásba, végül zsemlemorzsába forgatjuk.', 'Bő, forró olajban mindkét oldalát aranybarnára sütjük.', 'Papírtörlőre szedjük, hogy a felesleges olajat lecsöpögtessük.', 'Citromkarikákkal és friss salátával tálaljuk.'],
            46 => ['A brokkolit rózsáira szedjük, alaposan megmossuk.', 'Sós vízben puhára főzzük a brokkolit.', 'Hozzáadjuk a tejet és a tejszínt, összeforraljuk.', 'Reszelt sajtot keverünk bele, amíg elolvad.', 'Botmixerrel teljesen krémesre turmixoljuk.', 'Tányérokba merjük, kevés reszelt sajttal megszórva tálaljuk.'],
            47 => ['A tarhonyát olajon, folyamatosan kevergetve aranybarnára pirítjuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a felkockázott sertéshúst, pirospaprikával megszórjuk, átpirítjuk.', 'Sózzuk, borsozzuk, hozzáadjuk a felszeletelt paprikát, felöntjük vízzel.', 'Belekeverjük a pirított tarhonyát, lefedjük.', 'Lassú tűzön puhára pároljuk, amíg a tarhonya megszívja magát és megpuhul.'],
            48 => ['A tejet feltesszük forrni a vaníliával.', 'A tojásfehérjét kemény habbá verjük egy csipet sóval.', 'Kanállal habgaluskákat szaggatunk a forró tejbe, megfőzzük, majd kiszedjük.', 'A tojássárgáját cukorral habosra keverjük, vékony sugárban hozzáöntjük a forró tejet, folyamatos keverés mellett.', 'Visszaöntjük a lábasba, alacsony lángon krémesre melegítjük (nem forraljuk!).', 'A sodót tányérokba merjük, a habgaluskákat visszahelyezzük, hidegen vagy melegen tálaljuk.'],
            49 => ['A szárazbabot előző este hideg vízben beáztatjuk.', 'Másnap a babot leszűrjük, friss vízben feltesszük főni a füstölt csülökkel együtt.', 'Hozzáadjuk a megtisztított, feldarabolt zöldségeket (sárgarépa, hagyma).', 'Sózzuk, borsozzuk, lassú tűzön főzzük.', 'Amikor a bab és a csülök megpuhult, hozzáadjuk a felkarikázott kolbászt.', 'Összeforraljuk, friss kenyérrel tálaljuk.'],
            50 => ['A hagymát karikákra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a felkarikázott paprikát és a cikkekre vágott paradicsomot.', 'Sózzuk, pirospaprikával megszórjuk, közepes lángon pároljuk.', 'Amikor a zöldségek megpuhultak és levet engedtek, hozzáadjuk a felkarikázott kolbászt.', 'Pár percig együtt pirítjuk, majd beleütjük a tojásokat.', 'Óvatosan kevergetve addig sütjük, amíg a tojás megszilárdul, friss kenyérrel tálaljuk.'],
            51 => ['A burgonyát meghámozzuk, felkockázzuk.', 'Sós vízben puhára főzzük.', 'Lisztből és olajból világos rántást készítünk, hideg vízzel felöntjük, simára keverjük.', 'A rántást a burgonyához adjuk, összeforraljuk.', 'Frissen aprított petrezselyemmel megszórva tálaljuk.'],
            52 => ['A csirkemellet kiklopfoljuk, sózzuk, borsozzuk.', 'A kiklopfolt húsra egy szelet sonkát és egy szelet sajtot fektetünk.', 'Szorosan feltekerjük, a széleit fogpiszkálóval rögzítjük.', 'Serpenyőben kevés olajon körbepirítjuk a roládokat.', 'Előmelegített sütőben 180°C-on kb. 20-25 perc alatt készre sütjük.', 'Felszeletelve, rizzsel vagy burgonyapürével tálaljuk.'],
            53 => ['A csirkemellet sózzuk, borsozzuk, serpenyőben kevés olajon megsütjük.', 'A húst tepsibe fektetjük, paradicsomszeleteket teszünk rá.', 'Paradicsomszósszal meglocsoljuk.', 'Bőségesen megszórjuk reszelt sajttal.', 'Előmelegített sütőben addig sütjük, amíg a sajt ráolvad és aranybarnára pirul.', 'Rizzsel vagy friss salátával tálaljuk.'],
            54 => ['A sütőtököt meghámozzuk, magjait eltávolítjuk, felkockázzuk.', 'Egy tepsiben elterítjük, és előmelegített sütőben puhára sütjük (kb. 25-30 perc).', 'A megsült tököt lábasba tesszük, felöntjük tejjel és tejszínnel.', 'Sózzuk, borsozzuk, botmixerrel teljesen krémesre turmixoljuk.', 'A tökmagot száraz serpenyőben megpirítjuk.', 'A levest tányérokba merjük, pirított tökmaggal megszórva tálaljuk.'],
            55 => ['A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a felkockázott sertéshúst, pirospaprikával megszórjuk, átpirítjuk.', 'Sózzuk, borsozzuk, hozzáadjuk a felszeletelt paprikát, felöntjük vízzel.', 'Belekeverjük a rizst és a zöldborsót.', 'Lefedve, lassú tűzön puhára pároljuk, amíg a rizs megszívja a vizet.', 'Savanyúsággal tálaljuk.'],
            56 => ['Lisztből, cukorból, sütőporból, tojásból és olvasztott vajból tésztát keverünk.', 'A málnát óvatosan a tésztába forgatjuk, hogy ne törjenek össze.', 'Muffin papírral bélelt formákba adagoljuk a tésztát.', 'Előmelegített sütőben 180°C-on kb. 20 perc alatt aranybarnára sütjük.', 'Rácsra téve hagyjuk kihűlni.', 'Porcukorral meghintve vagy cukormázzal leöntve tálaljuk.'],
            57 => ['A sárgaborsót előző este hideg vízben beáztatjuk.', 'Másnap a borsót leszűrjük, friss vízben feltesszük főni.', 'Sózzuk, hozzáadjuk az apróra vágott hagymát és kevés olajat.', 'Puhára főzzük, majd botmixerrel pürésítjük vagy összetörjük.', 'A kolbászt felkarikázzuk, serpenyőben átpirítjuk.', 'A főzeléket a pirított kolbásszal tálaljuk.'],
            58 => ['A csokoládét és a vajat vízgőz felett megolvasztjuk, majd langyosra hűtjük.', 'Hozzáadjuk a cukrot, a tojásokat egyenként, végül a lisztet.', 'A diót durvára vágjuk, a masszába keverjük.', 'Kivajazott, lisztezett tepsibe öntjük a tésztát.', 'Előmelegített sütőben 180°C-on kb. 25-30 percig sütjük (a közepe maradjon kissé nedves).', 'Kihűlés után kockákra vágva tálaljuk.'],
            59 => ['A tésztát bő, sós vízben kifőzzük, leszűrjük.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a felkarikázott paprikát és a cikkekre vágott paradicsomot, lecsót készítünk.', 'Sózzuk, borsozzuk, pirospaprikával megszórjuk.', 'Hozzáadjuk a felkarikázott kolbászt, átpirítjuk.', 'A kifőtt tésztát összekeverjük a kolbászos lecsóval és azonnal tálaljuk.'],
            60 => ['A zabpelyhet egy lábasba tesszük, felöntjük tejjel.', 'Közepes lángon, folyamatosan kevergetve megfőzzük, amíg a zabpehely besűrűsödik.', 'Mézzel édesítjük, elkeverjük.', 'Tányérba szedjük, friss gyümölccsel és durvára vágott dióval megszórjuk.', 'Azonnal tálaljuk, amíg meleg.'],
            61 => ['A sertéshúst megmossuk, kockákra vágjuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a húst, és addig pirítjuk, amíg kifehéredik.', 'Felöntjük vízzel, hozzáadjuk a megtisztított és feldarabolt zöldségeket.', 'Sózzuk, borsozzuk, babérlevelet adunk hozzá.', 'Lassú tűzön puhára főzzük, friss kenyérrel tálaljuk.'],
            62 => ['A csirkemellet sózzuk, borsozzuk, kevés olajjal megkenjük, grillen megsütjük.', 'A salátát megmossuk, leveleit nagyobb darabokra tépkedjük.', 'A kenyeret kockákra vágjuk, serpenyőben aranybarnára, ropogósra pirítjuk (ez lesz a kruton).', 'A megsült csirkét vékony szeletekre vágjuk.', 'A salátaleveleket tányérra halmozzuk, ráfektetjük a csirkeszeleteket, rászórjuk a krutont.', 'Parmezánforgáccsal és majonézes öntettel tálaljuk.'],
            63 => ['A cukkinit megmossuk, karikákra vágjuk.', 'A darált húst apróra vágott hagymával, sóval, borssal olajon megpároljuk.', 'Egy kivajazott tepsibe rétegezzük: egy sor cukkini, egy réteg húsos ragu.', 'A rétegezést addig ismételjük, amíg a hozzávalók el nem fogynak.', 'A tetejét bőségesen megszórjuk reszelt sajttal.', 'Előmelegített sütőben 180°C-on kb. 25-30 perc alatt összesütjük.'],
            64 => ['A csirkemellet megmossuk, feldaraboljuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a csirkét, sózzuk, borsozzuk, tárkonnyal megszórjuk.', 'Felöntjük vízzel és tejjel, hozzáadjuk a feldarabolt zöldségeket.', 'Lassú tűzön puhára főzzük.', 'Tejfölös habarással sűrítjük, összeforraljuk, friss kenyérrel tálaljuk.'],
            65 => ['A paradicsomot, uborkát, paprikát megmossuk, felkockázzuk.', 'A hagymát vékony karikákra vágjuk.', 'A zöldségeket egy nagy tálban összekeverjük az olívabogyóval és a felkockázott feta sajttal.', 'Olívaolajjal meglocsoljuk, sóval, borssal ízesítjük.', 'Óvatosan átforgatjuk, hogy a feta ne törjön össze.', 'Azonnal, friss kenyérrel tálaljuk.'],
            66 => ['A burgonyát héjában megfőzzük, meghámozzuk, még melegen áttörjük.', 'A lisztet összekeverjük a burgonyával, vajjal, élesztővel és sóval, tésztává dagasztjuk.', 'A tésztát letakarva a duplájára kelesztjük.', 'Kinyújtjuk, pogácsaszaggatóval kiszaggatjuk, sütőpapírral bélelt tepsibe rakjuk.', 'A tetejét megkenjük tojással, megszórjuk reszelt sajttal.', 'Előmelegített sütőben 180°C-on aranybarnára sütjük.'],
            67 => ['A penne tésztát bő, sós vízben kifőzzük, leszűrjük.', 'A fokhagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a spenótot, sózzuk, borsozzuk, puhára pároljuk.', 'Tejszínnel és tejföllel dúsítjuk, összeforraljuk.', 'A leszűrt tésztát összekeverjük a spenótos mártással.', 'Reszelt sajttal megszórva, azonnal tálaljuk.'],
            68 => ['A céklát meghámozzuk, felkockázzuk.', 'Sós vízben puhára főzzük.', 'Tejszínnel dúsítjuk, botmixerrel teljesen krémesre turmixoljuk.', 'Tejföllel gazdagítjuk, összeforraljuk.', 'Tányérokba merjük, kevés tejföllel a tetején tálaljuk.'],
            69 => ['A csirkemellet sózzuk, borsozzuk, serpenyőben kevés olajon megsütjük.', 'A gombát felszeleteljük, az apróra vágott hagymával olajon megpároljuk.', 'Tejszínnel összekeverjük a gombás ragut, összeforraljuk.', 'A mártást a csirkére öntjük.', 'Tésztával vagy rizzsel tálaljuk.'],
            70 => ['Az élesztőt langyos tejben egy kevés cukorral felfuttatjuk.', 'Lisztből, vajból, cukorból, tojásból és a felfutott élesztőből tésztát dagasztunk.', 'A tésztát letakarva a duplájára kelesztjük.', 'Kinyújtjuk, megszórjuk a cukorral elkevert darált dióval, majd szorosan feltekerjük.', 'Kalácsformába fektetjük, újra kelesztjük, a tetejét megkenjük tojással.', 'Előmelegített sütőben 180°C-on 35-40 perc alatt aranybarnára sütjük.'],
            71 => ['A csirkemellet vékony csíkokra vágjuk.', 'A paprikát és paradicsomot felszeleteljük.', 'Wokban vagy nagy serpenyőben olajat forrósítunk, beletesszük a csirkét, magas hőfokon megpirítjuk.', 'Hozzáadjuk a zöldségeket, sózzuk, borsozzuk.', 'Folyamatosan kevergetve, magas hőfokon 3-4 percig pirítjuk.', 'Azonnal, rizzsel vagy tésztával tálaljuk.'],
            72 => ['A szárazbabot előző este hideg vízben beáztatjuk.', 'Másnap a babot leszűrjük, friss vízben feltesszük főni.', 'Hozzáadjuk az apróra vágott hagymát, fokhagymát, paradicsomszószt.', 'Sózzuk, borsozzuk, lassú tűzön főzzük.', 'Amikor a bab majdnem megpuhult, hozzáadjuk a felkarikázott kolbászt.', 'Teljesen puhára főzzük, friss kenyérrel tálaljuk.'],
            73 => ['A tejfölt összekeverjük reszelt sajttal, sóval, borssal.', 'A kenyérszeleteket sütőpapírral bélelt tepsire fektetjük.', 'A sajtos-tejfölös krémet vastagon a kenyérszeletekre kenjük.', 'Előmelegített sütőben addig sütjük, amíg a sajt megolvad és a teteje aranybarnára pirul.', 'Forrón, azonnal tálaljuk.'],
            74 => ['A zöldségeket (sárgarépa, burgonya, zeller) meghámozzuk, felkockázzuk.', 'Sós vízben puhára főzzük a zöldségeket.', 'Tejszínnel dúsítjuk, botmixerrel teljesen krémesre turmixoljuk.', 'A kenyeret kockákra vágjuk, serpenyőben aranybarnára pirítjuk.', 'A levest tányérokba merjük, pirított kenyérkockákkal megszórva tálaljuk.'],
            75 => ['A csirkemellet vékony csíkokra vágjuk, sózzuk, borsozzuk, serpenyőben megsütjük.', 'A tortillákat száraz serpenyőben átmelegítjük.', 'A salátát megmossuk, a paradicsomot és paprikát felkockázzuk.', 'A tortillákra salátát halmozunk, rátesszük a csirkét és a zöldségeket.', 'Öntettel meglocsoljuk, szorosan feltekerjük.', 'Félbevágva, azonnal tálaljuk.'],
            76 => ['A burgonyát meghámozzuk, felkockázzuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a burgonyát, pirospaprikával megszórjuk, gyakran kevergetve megpirítjuk.', 'Sózzuk, borsozzuk, közepes lángon puhára sütjük.', 'A tésztát bő, sós vízben kifőzzük, leszűrjük.', 'A leszűrt tésztát összekeverjük a pirított burgonyával, azonnal tálaljuk.'],
            77 => ['A csokoládét és a vajat vízgőz felett megolvasztjuk.', 'Hozzáadjuk a cukrot, a tojásokat egyenként, végül a lisztet és a kakaóport.', 'Alaposan összekeverjük, hogy sima masszát kapjunk.', 'Kivajazott, lisztezett tortaformába öntjük a tésztát.', 'Előmelegített sütőben 180°C-on kb. 30-35 percig sütjük.', 'Kihűlés után csokoládékrémmel vonjuk be, szeletelve tálaljuk.'],
            78 => ['A zöldségeket (paradicsom, hagyma, paprika) felszeleteljük, olajon megpároljuk.', 'Paradicsomszószt adunk hozzá, sózzuk, borsozzuk, fűszerezzük, zöldséges ragut készítünk.', 'Egy kivajazott tepsibe vékony réteg ragut kenünk, majd lasagne lapokat fektetünk rá.', 'A lasagne lapokra ricottát és reszelt sajtot szórunk, majd újra ragu következik.', 'A rétegezést addig ismételjük, amíg a hozzávalók el nem fogynak, a tetejére bőséges sajt kerüljön.', 'Előmelegített sütőben 180°C-on kb. 30-35 perc alatt aranybarnára sütjük.'],
            79 => ['A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a darált húst, és fehéredésig pirítjuk.', 'Hozzáadjuk a babot (előzőleg beáztatva és megfőzve vagy konzerv), a paradicsomszószt és a fokhagymát.', 'Sózzuk, borsozzuk, chilivel fűszerezzük.', 'Lassú tűzön kb. 20-25 percig főzzük, hogy az ízek összeérjenek.', 'Rizzsel vagy friss kenyérrel tálaljuk.'],
            80 => ['Lisztből, tojásból, tejből, cukorból palacsintatésztát keverünk, vékony palacsintákat sütünk.', 'A túrót áttörjük, cukorral, vaníliás cukorral és egy kevés tejföllel krémesre keverjük.', 'A palacsintákat megtöltjük a túrós krémmel, feltekerjük.', 'A megtöltött palacsintákat tepsibe fektetjük, tejföllel meglocsoljuk.', 'Előmelegített sütőben kb. 10 perc alatt átmelegítjük.', 'Porcukorral meghintve tálaljuk.'],
            81 => ['A sertéshúst vékony csíkokra vágjuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a húst, és bőségesen megszórjuk frissen őrölt borssal.', 'Felöntjük tejszínnel, sózzuk.', 'Lassú tűzön, lefedve puhára pároljuk.', 'Rizzsel vagy tésztával, savanyúsággal tálaljuk.'],
            82 => ['A csirkecombokat megmossuk, szárazra töröljük.', 'Sózzuk, borsozzuk, fűszerezzük ízlés szerint.', 'Kevés olajjal megkenjük a combokat, tepsibe fektetjük.', 'Előmelegített sütőben 180°C-on kb. 40-45 perc alatt ropogósra sütjük.', 'Citromkarikákkal és friss salátával tálaljuk.'],
            83 => ['A karfiolt rózsáira szedjük, megmossuk, sós vízben előfőzzük (kb. 5 perc).', 'Leszűrjük, lecsepegtetjük, majd kivajazott tepsibe terítjük.', 'Tejszínt, tejet, reszelt sajtot, sót összekeverünk, a karfiolra öntjük.', 'A tetejét bőségesen megszórjuk reszelt sajttal.', 'Előmelegített sütőben 180°C-on kb. 20-25 perc alatt aranybarnára sütjük.'],
            84 => ['A burgonyát meghámozzuk, felkockázzuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a burgonyát, felöntjük vízzel és tejjel.', 'Sózzuk, borsozzuk, puhára főzzük, majd botmixerrel krémesre turmixoljuk.', 'A szalonnát apró kockákra vágjuk, serpenyőben ropogósra sütjük.', 'A levest tányérokba merjük, pirított szalonnapörccel megszórva tálaljuk.'],
            85 => ['A cukkinit megmossuk, félbevágjuk, a belsejét kanállal kivájjuk.', 'A darált húst apróra vágott hagymával, sóval, borssal, olajon megpároljuk.', 'A kivájt cukkinikat szorosan megtöltjük a húsos töltelékkel.', 'Kivajazott tepsibe sorakoztatjuk a megtöltött cukkinikat.', 'Bőségesen megszórjuk reszelt sajttal.', 'Előmelegített sütőben 180°C-on kb. 25-30 perc alatt készre sütjük.'],
            86 => ['A csirkemellet vékony csíkokra vágjuk, fűszeres pácban (olaj, só, bors, fokhagyma) legalább 1 órán át pácoljuk.', 'Serpenyőben kevés olajon megsütjük a pácolt csirkét.', 'A pitákat megmelegítjük.', 'A salátát megmossuk, feldaraboljuk.', 'A pitákba salátát halmozunk, rátesszük a sült csirkét.', 'Öntettel meglocsoljuk, azonnal tálaljuk.'],
            87 => ['A tejet feltesszük forrni a vaníliával és a cukorral.', 'A keményítőt hideg tejben simára keverjük.', 'A forró tejhez öntjük a keményítős keveréket, folyamatosan kevergetve.', 'Alacsony lángon sűrűre főzzük (kb. 2-3 perc).', 'Poharakba adagoljuk, hűtőben lehűtjük.', 'Tejszínhabbal és gyümölccsel díszítve tálaljuk.'],
            88 => ['A csirkemellet vékony csíkokra vágjuk, sózzuk, borsozzuk, serpenyőben megsütjük.', 'A tortillákra bőségesen reszelt sajtot szórunk.', 'A sajtos tortilla egyik felére halmozzuk a sült csirkét.', 'A tortillát félbehajtjuk.', 'Serpenyőben mindkét oldalát aranybarnára, ropogósra sütjük, amíg a sajt megolvad.', 'Cikkekre vágva, salátával tálaljuk.'],
            89 => ['A fokhagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a paradicsomszószt, sózzuk, borsozzuk, bazsalikommal fűszerezzük.', 'Lassú tűzön 15-20 percig összeforraljuk a mártást.', 'A tésztát bő, sós vízben kifőzzük, leszűrjük.', 'A leszűrt tésztát összekeverjük a paradicsomos mártással.', 'Reszelt sajttal megszórva, azonnal tálaljuk.'],
            90 => ['Lisztből, vajból, cukorból, tojásból omlós tésztát gyúrunk.', 'A darált diót belegyúrjuk a tésztába.', 'A tésztát kinyújtjuk, pogácsaszaggatóval vagy késsel tetszőleges formákra vágjuk.', 'Sütőpapírral bélelt tepsibe rakjuk a süteményeket.', 'Előmelegített sütőben 180°C-on világosra sütjük (kb. 10-12 perc).', 'Porcukorral bőségesen megszórva tálaljuk.'],
            91 => ['A sertésszüzet megmossuk, szárazra töröljük.', 'Sózzuk, borsozzuk, fűszerezzük ízlés szerint.', 'Serpenyőben kevés olajon körbepirítjuk, hogy kérget kapjon.', 'Előmelegített sütőben 180°C-on kb. 20-25 perc alatt készre sütjük.', 'Sütés után 5-10 percig pihentetjük, majd felszeleteljük.', 'Rizzsel, sült burgonyával és salátával tálaljuk.'],
            92 => ['A hagymát apróra vágjuk, olajon megdinszteljük.', 'Hozzáadjuk a rizst, és üvegesre pirítjuk.', 'Felöntjük vízzel (kétszeres mennyiség), sózzuk.', 'Hozzáadjuk a zöldborsót.', 'Lefedve, alacsony lángon puhára pároljuk, amíg a rizs megszívja a vizet.', 'Friss petrezselyemmel megszórva tálaljuk.'],
            93 => ['A nokedlit bő, sós vízben kifőzzük, leszűrjük, lecsepegtetjük.', 'A tojásokat felverjük, sózzuk.', 'Serpenyőben olajat forrósítunk, beletesszük a nokedlit, átpirítjuk.', 'Ráöntjük a felvert tojásokat, folyamatosan kevergetjük.', 'Addig sütjük, amíg a tojás megszilárdul, de még szaftos marad.', 'Tejföllel meglocsolva, savanyúsággal tálaljuk.'],
            94 => ['Az élesztőt langyos tejben egy kevés cukorral felfuttatjuk.', 'Lisztből, vajból, tejfölből, sóból és a felfutott élesztőből tésztát dagasztunk.', 'Reszelt sajtot gyúrunk a tésztába.', 'A tésztát letakarva a duplájára kelesztjük.', 'Kinyújtjuk, kiszaggatjuk, sütőpapírral bélelt tepsibe rakjuk, a tetejét megkenjük tojással és megszórjuk sajttal.', 'Előmelegített sütőben 180°C-on aranybarnára sütjük.'],
            95 => ['A csirkemellet kockákra vágjuk.', 'A hagymát apróra vágjuk, olajon megdinszteljük.', 'Curry porral megszórjuk, hozzáadjuk a csirkét, átforgatjuk.', 'Felöntjük tejszínnel, sózzuk.', 'Lassú tűzön, lefedve puhára pároljuk.', 'Rizzsel tálaljuk.'],
            96 => ['A meggyet kimagozzuk.', 'Vízben cukorral és fahéjjal feltesszük főni.', 'Amikor a meggy megpuhult, tejszínnel dúsítjuk, összeforraljuk.', 'Lehűtjük, majd teljesen hidegre hűtve tálaljuk.'],
            97 => ['A makarónit bő, sós vízben kifőzzük, leszűrjük.', 'Tejszínt, tejet, reszelt sajtot és tejfölt összekeverünk, sózzuk, felforraljuk.', 'A leszűrt tésztát összekeverjük a sajtos szósszal, kivajazott tepsibe öntjük.', 'A tetejét bőségesen megszórjuk reszelt sajttal.', 'Előmelegített sütőben 180°C-on 20-25 perc alatt aranybarnára sütjük.'],
            98 => ['A sertés rostélyost kiklopfoljuk, sózzuk, borsozzuk.', 'A hagymát vékony karikákra vágjuk.', 'Serpenyőben kevés olajon a húst elkezdjük sütni.', 'Amikor az egyik oldala megsült, megfordítjuk, és mellédobjuk a hagymakarikákat.', 'A hagymát aranybarnára pirítjuk, közben a hús is megsül.', 'A pirított hagymával a hús tetején, sült burgonyával tálaljuk.'],
            99 => ['A tojássárgáját cukorral habosra keverjük, majd hozzáadjuk a mascarponét, simára keverjük.', 'A kávét lefőzzük, kihűtjük.', 'A piskótát rövid időre a kávéba mártogatjuk, majd egy tál aljára fektetjük.', 'A kávés piskótára mascarponés krémet kenünk, friss eperszeleteket teszünk rá.', 'A rétegezést addig ismételjük, amíg a hozzávalók el nem fogynak.', 'Hűtőben legalább 4 órát pihentetjük, kakaóporral megszórva tálaljuk.'],
            100 => ['A tojásokat felverjük, sózzuk, borsozzuk.', 'A paprikát és paradicsomot megmossuk, felkockázzuk.', 'Serpenyőben kevés olajat forrósítunk, beletesszük a zöldségeket, megpirítjuk.', 'Ráöntjük a felvert tojásokat, reszelt sajttal megszórjuk.', 'Amikor a tojás alja megszilárdult, az omlettet félbehajtjuk.', 'Mindkét oldalát aranybarnára sütjük, friss kenyérrel tálaljuk.'],
        ];

        $records = [];
        foreach ($recipeSteps as $recipeId => $steps) {
            foreach ($steps as $order => $description) {
                $records[] = [
                    'description' => $description,
                    'recipe_id' => $recipeId,
                    'order' => $order + 1,
                ];
            }
        }

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('step')->insert($chunk);
        }
    }
}