<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StepSeeder extends Seeder
{
    public function run(): void
    {
        // Minden lépésben szerepel a felhasznált alapanyag és annak pontos mennyisége
        // (egyezik az IngredientRecipeSeeder mennyiségeivel).
        $recipeSteps = [
            1 => [ // Gulyásleves
                '800 g marhahúst megmosunk és 2 cm-es kockákra vágunk.',
                '2 db hagymát apróra vágunk, és 3 evőkanál olajon üvegesre pirítjuk.',
                'Levesszük a tűzről, megszórjuk 2 evőkanál pirospaprika őrleménnyel, hozzáadjuk a húst, és fehéredésig pirítjuk.',
                'Felöntjük 2000 ml vízzel, hozzáadunk 2 teáskanál sót, 0,5 teáskanál borsot és 2 db babérlevelet, majd fedő alatt 1 órán át főzzük.',
                'Hozzáadunk 600 g felkockázott burgonyát, 2 db karikára vágott sárgarépát, 2 db felcsíkozott paprikát és 1 db felkockázott paradicsomot.',
                'Lassú tűzön további 30 percig főzzük, amíg a hús és a zöldségek megpuhulnak, majd forrón tálaljuk.',
            ],
            2 => [ // Csirkepörkölt
                '800 g csirkecombot megmosunk, és az ízületeknél feldarabolunk.',
                '2 db hagymát apróra vágunk, és 3 evőkanál olajon üvegesre pirítjuk.',
                'Levesszük a tűzről, megszórjuk 2 evőkanál pirospaprika őrleménnyel, hozzáadjuk a csirkét, és átforgatjuk.',
                'Felöntjük 300 ml vízzel, hozzáadunk 2 db felszeletelt paprikát és 1 db felkockázott paradicsomot.',
                '1,5 teáskanál sóval és 0,5 teáskanál borssal ízesítjük, és fedő alatt, lassú tűzön 40 percig pároljuk.',
                '200 g tejföllel és 500 g kifőzött nokedlivel tálaljuk.',
            ],
            3 => [ // Túrós csusza
                '400 g tésztát bő vízben, 2 teáskanál sóval kifőzünk, majd leszűrünk.',
                '150 g szalonnát apró kockákra vágunk, és serpenyőben ropogósra sütjük.',
                '400 g túrót villával szétmorzsolunk.',
                'A forró tésztát összekeverjük a szalonna kisült zsírjával és 200 g tejföllel.',
                'Tányérra halmozzuk, megszórjuk a túróval, a tetejére 100 g tejfölt és a szalonnapörcöt tesszük.',
                'Azonnal tálaljuk, amíg a tészta forró.',
            ],
            4 => [ // Rakott krumpli
                '1000 g burgonyát héjában puhára főzünk, meghámozzuk és karikákra vágjuk.',
                '6 db tojást 10 perc alatt keményre főzünk, meghámozzuk és felkarikázzuk.',
                '200 g kolbászt vékony karikákra vágunk.',
                'Egy tepsit kikenünk 30 g vajjal, és rétegezzük a burgonyát, a tojást és a kolbászt; a rétegeket összesen 1,5 teáskanál sóval és 0,5 teáskanál borssal ízesítjük.',
                'A rétegek közé és a tetejére összesen 400 g tejfölt kenünk; a legfelső réteg burgonya legyen.',
                'Előmelegített sütőben 180°C-on 30 percig aranybarnára sütjük.',
            ],
            5 => [ // Halászlé
                '1000 g pontyot, 500 g harcsát és 300 g keszeget megtisztítunk, levágjuk a fejüket és farkukat (ezeket félretesszük), a halak törzsét pedig kifilézzük, és a filéket 3 cm-es szeletekre vágjuk.',
                'A halfejeket és farkakat 3 db felszeletelt hagymával 2500 ml hideg vízben feltesszük főni.',
                'Lassú tűzön 1 órán át főzzük, majd az alaplevet szitán átpasszírozzuk.',
                'Az alaplébe keverünk 3 evőkanál pirospaprika őrleményt és 2 teáskanál sót, majd hozzáadunk 1 db felkarikázott paprikát és 1 db paradicsomot.',
                'Beletesszük a halszeleteket, és keverés nélkül, csak a lábast rázogatva 15 percig főzzük.',
                '300 g tésztát külön kifőzünk, és a halászlé mellé tálaljuk.',
            ],
            6 => [ // Lángos
                '25 g élesztőt 300 ml langyos tejben 5 g cukorral felfuttatunk.',
                '500 g lisztet tálba szitálunk, hozzáadjuk a felfutott élesztőt és 1 teáskanál sót.',
                'Sima tésztává dagasztjuk, majd letakarva 45 percig, a duplájára kelesztjük.',
                'A tésztát 8 részre osztjuk, és olajos kézzel tenyérnyi lapokká húzzuk.',
                '500 ml olajat felforrósítunk, és a lángosokat mindkét oldalukon aranybarnára sütjük.',
                'A lángosokat 200 g tejföllel megkenjük, és 150 g reszelt sajttal megszórva tálaljuk.',
            ],
            7 => [ // Palacsinta
                '200 g lisztet, 2 db tojást, 400 ml tejet, 20 g cukrot és 0,25 teáskanál sót csomómentesre keverünk.',
                'A tésztába 1 evőkanál olajat keverünk, és 15 percig pihentetjük.',
                'Egy serpenyőt 1 evőkanál olajjal kikenünk, felforrósítjuk, és vékonyan belemerünk a tésztából.',
                'Mindkét oldalát aranybarnára sütjük; így összesen kb. 12 palacsintát sütünk.',
                'A palacsinták felét 150 g baracklekvárral, a másik felét 30 g kakaópor és 40 g porcukor keverékével töltjük, és feltekerve tálaljuk.',
            ],
            8 => [ // Székelykáposzta
                '800 g sertéshúst megmosunk és 2 cm-es kockákra vágunk.',
                '2 db hagymát apróra vágunk, 3 evőkanál olajon üvegesre pirítjuk, majd hozzáadunk 2 gerezd zúzott fokhagymát.',
                'Levesszük a tűzről, megszórjuk 2 evőkanál pirospaprika őrleménnyel, hozzáadjuk a húst, és fehéredésig pirítjuk.',
                'Felöntjük 700 ml vízzel, hozzáadunk 1 teáskanál sót, 0,5 teáskanál borsot és 2 db babérlevelet, majd 40 percig pároljuk.',
                'Hozzáadunk 1000 g átmosott, lecsöpögtetett savanyú káposztát, és további 40 percig főzzük.',
                '200 g tejfölt 20 g liszttel simára keverünk, a káposztához adjuk, összeforraljuk, és 100 g tejföllel a tetején tálaljuk.',
            ],
            9 => [ // Paprikás csirke
                '1000 g csirkecombot megmosunk, és az ízületeknél kettévágunk.',
                '2 db hagymát apróra vágunk, és 3 evőkanál olajon üvegesre dinszteljük.',
                'Levesszük a tűzről, belekeverünk 2 evőkanál pirospaprika őrleményt, hozzáadjuk a csirkét, és átforgatjuk.',
                'Hozzáadunk 1 db felszeletelt paprikát és 1 db felkockázott paradicsomot, felöntjük 300 ml vízzel, 1,5 teáskanál sóval ízesítjük, és fedő alatt 40 percig pároljuk.',
                '300 g tejfölt 20 g liszttel simára keverünk, a szaftba keverjük, és összeforraljuk.',
                '500 g kifőzött nokedlivel tálaljuk.',
            ],
            10 => [ // Meggyes pite
                '400 g lisztet, 200 g hideg vajat, 100 g cukrot, 1 teáskanál sütőport és 2 db tojást omlós tésztává gyúrunk, két részre osztjuk, és 30 percre hűtőbe tesszük.',
                'A tészta egyik felét kinyújtjuk, és sütőpapírral bélelt tepsibe fektetjük.',
                '800 g kimagozott meggyet 80 g cukorral, 1 teáskanál fahéjjal és 2 evőkanál keményítővel összekeverünk, és a tésztára terítjük.',
                'A másik tésztalapot kinyújtjuk, csíkokra vágjuk, és rácsos mintában a meggyre fektetjük.',
                'Előmelegített sütőben 180°C-on 40 percig aranybarnára sütjük.',
                'Kihűlés után 30 g porcukorral meghintjük, és 8 szeletre vágjuk.',
            ],
            11 => [ // Bolognai spagetti
                '1 db hagymát és 2 gerezd fokhagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 500 g darált húst, és fehéredésig pirítjuk.',
                'Belekeverünk 1 db lereszelt sárgarépát, 1 db apróra vágott zellert és 2 db felkockázott paradicsomot.',
                'Felöntjük 500 ml paradicsomszósszal, és 1 teáskanál sóval, 0,5 teáskanál borssal, 1 teáskanál bazsalikommal fűszerezzük.',
                'Lassú tűzön, időnként megkeverve 1 órán át főzzük a mártást.',
                '400 g spagettit bő vízben kifőzünk, leszűrünk, és a szósszal, 40 g reszelt parmezánnal megszórva tálaljuk.',
            ],
            12 => [ // Csirkemell saláta
                '300 g csirkemellet 0,5 teáskanál sóval, 0,25 teáskanál borssal és 1 evőkanál olajjal bedörzsölünk.',
                'Grillserpenyőben mindkét oldalát 5-6 percig sütjük, majd 5 percig pihentetjük.',
                '1 fej salátát megmosunk, a leveleit falatnyi darabokra tépkedjük.',
                '2 db paradicsomot cikkekre, 1 db uborkát karikákra vágunk, és a salátához adjuk.',
                '1 db citrom levét 1 evőkanál olajjal összekeverjük, és a salátára locsoljuk.',
                'A csirkét felszeleteljük, a saláta tetejére fektetjük, és azonnal tálaljuk.',
            ],
            13 => [ // Töltött paprika
                '8 db töltenivaló paprika tetejét levágjuk, a magházát és az ereit eltávolítjuk.',
                '100 g rizst félpuhára főzünk, 1 db hagymát apróra vágunk.',
                '500 g darált húst összekeverünk a rizzsel, a hagymával, 1 db tojással, 1,5 teáskanál sóval és 0,5 teáskanál borssal.',
                'A paprikákat lazán megtöltjük a töltelékkel, és egy lábasba állítjuk őket.',
                '1000 ml paradicsomszószt 30 g cukorral és 0,5 teáskanál sóval ízesítünk, és a paprikákra öntjük.',
                'Fedő alatt, lassú tűzön 50 percig főzzük, és melegen tálaljuk.',
            ],
            14 => [ // Borsóleves
                '1 db hagymát apróra vágunk, és 30 g vajon üvegesre dinszteljük.',
                'Hozzáadunk 500 g zöldborsót, és felöntjük 700 ml vízzel és 200 ml tejjel.',
                '1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és 15 percig főzzük.',
                'Hozzáadunk 100 ml tejszínt, majd botmixerrel krémesre turmixoljuk.',
                '2 szelet kenyeret kockákra vágunk, és 1 evőkanál olajon aranybarnára pirítjuk.',
                'A levest tányérokba merjük, és a pirított kenyérkockákkal megszórva tálaljuk.',
            ],
            15 => [ // Rántott sajt
                '600 g trappista sajtot 1 cm vastag szeletekre vágunk.',
                '3 db tojást felverünk; 100 g lisztet és 200 g zsemlemorzsát külön tányérra szórunk.',
                'A sajtszeleteket lisztbe, tojásba, majd zsemlemorzsába forgatjuk; a tojásos és morzsás lépést megismételjük a vastagabb bundáért.',
                '800 g burgonyát meghámozunk és hasábokra vágunk.',
                '500 ml olajat felforrósítunk; előbb a burgonyát sütjük ropogósra, és megszórjuk 1 teáskanál sóval, majd a sajtokat oldalanként 1-2 perc alatt aranybarnára sütjük.',
                'Papírtörlőn lecsöpögtetjük, és a hasábburgonyával tálaljuk.',
            ],
            16 => [ // Zserbó
                '20 g élesztőt 100 ml langyos tejben felfuttatunk.',
                '500 g lisztet 250 g vajjal elmorzsolunk, hozzáadunk 50 g cukrot, 1 db tojássárgáját és a felfutott élesztőt, majd tésztává gyúrjuk, és 3 egyenlő részre osztjuk.',
                '300 g darált diót 150 g cukorral összekeverünk.',
                'Az első lapot tepsibe tesszük, megkenjük 200 g baracklekvárral, megszórjuk a diós cukor felével; rá jön a második lap, újabb 200 g lekvár, a maradék dió, végül a harmadik lap.',
                'Előmelegített sütőben 180°C-on 35 percig sütjük, majd kihűtjük.',
                '150 g csokoládét 30 g vajjal vízgőz felett megolvasztunk, a zserbó tetejére kenjük, és megdermedés után 12 szeletre vágjuk.',
            ],
            17 => [ // Fokhagymakrémleves
                '10 gerezd fokhagymát meghámozunk és vékonyan felszeletelünk.',
                '40 g vajat felolvasztunk, a fokhagymát alacsony lángon 5 perc alatt üvegesre pároljuk, majd megszórjuk 20 g liszttel.',
                'Felöntjük 600 ml vízzel és 300 ml tejjel, 1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és 15 percig főzzük.',
                'Hozzáadunk 200 ml tejszínt, és botmixerrel krémesre turmixoljuk.',
                '4 szelet kenyeret kockákra vágunk, és száraz serpenyőben aranybarnára pirítjuk.',
                'A levest tányérokba merjük, és a kenyérkockákkal, valamint 80 g reszelt sajttal megszórva tálaljuk.',
            ],
            18 => [ // Marhapörkölt
                '1200 g marhahúst megmosunk és 3 cm-es kockákra vágunk.',
                '3 db hagymát apróra vágunk, és 50 g zsíron aranysárgára pirítjuk.',
                'Levesszük a tűzről, belekeverünk 2 evőkanál pirospaprika őrleményt, majd hozzáadjuk a húst és 2 gerezd zúzott fokhagymát.',
                'Hozzáadunk 1 db felszeletelt paprikát és 1 db felkockázott paradicsomot, és 2 teáskanál sóval, 0,5 teáskanál borssal fűszerezzük.',
                'Felöntjük 500 ml vízzel, és fedő alatt, lassú tűzön, időnként megkeverve 2 órán át pároljuk.',
                '300 g csipetkét forrásban lévő vízben kifőzünk, és a pörkölttel tálaljuk.',
            ],
            19 => [ // Dobos torta
                '6 db tojást 120 g cukorral habosra verünk, majd óvatosan beleforgatunk 120 g lisztet.',
                'A masszából 6 vékony, 24 cm-es lapot sütünk sütőpapíron, 200°C-on laponként 5-6 percig.',
                '4 db tojást 200 g cukorral gőz felett sűrűre főzünk, belekeverünk 150 g felolvasztott csokoládét, majd kihűtjük.',
                '250 g szobahőmérsékletű vajat habosra keverünk, és hozzáadjuk a kihűlt csokoládés alapot.',
                'Öt lapot a krémmel megkenve egymásra rétegezünk, a torta tetejét és oldalát is bekenjük.',
                '150 g cukrot aranybarnára karamellizálunk, a hatodik lapra öntjük, gyorsan 10 cikkre vágjuk, és a torta tetejére helyezzük.',
            ],
            20 => [ // Káposztás tészta
                '800 g káposztát lereszelünk, 1 teáskanál sóval összekeverjük, 15 percig állni hagyjuk, majd kinyomkodjuk.',
                '4 evőkanál olajat felhevítünk, megszórjuk 10 g cukorral, és enyhén karamellizáljuk.',
                'Hozzáadjuk a káposztát, és közepes lángon, gyakran kevergetve 25 percig pirítjuk.',
                '0,5 teáskanál sóval és 0,5 teáskanál borssal ízesítjük.',
                '400 g kockatésztát bő vízben kifőzünk, és leszűrünk.',
                'A tésztát összekeverjük a pirított káposztával, és azonnal tálaljuk.',
            ],
            21 => [ // Sertésborda rántva
                '600 g sertéskarajt 4 szeletre vágunk, kiklopfolunk, és 1 teáskanál sóval, 0,25 teáskanál borssal fűszerezünk.',
                '2 db tojást felverünk; 80 g lisztet és 150 g zsemlemorzsát külön tányérra szórunk.',
                'A szeleteket lisztbe, tojásba, majd zsemlemorzsába forgatjuk.',
                '400 ml olajat felforrósítunk, és a húsokat oldalanként 4 percig aranybarnára sütjük.',
                'Papírtörlőn lecsöpögtetjük, és 1 db citrom karikáival tálaljuk.',
            ],
            22 => [ // Paradicsomleves
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                '8 db paradicsomot felkockázunk, a hagymához adjuk, és felöntjük 500 ml vízzel.',
                '1 teáskanál sóval, 20 g cukorral és 1 teáskanál szárított bazsalikommal ízesítjük.',
                '20 percig főzzük, majd botmixerrel simára turmixoljuk.',
                '100 g tejföllel dúsítjuk, és összeforraljuk.',
                '2 szelet kenyeret kockára vágunk, száraz serpenyőben megpirítjuk, és a levesre szórva tálaljuk.',
            ],
            23 => [ // Töltött káposzta
                '1500 g savanyú káposztából leválasztunk 12 egész levelet, a maradékot átmossuk, lecsöpögtetjük és felaprítjuk (ez lesz a vágott káposzta).',
                '600 g darált húst összekeverünk 100 g nyers rizzsel, 1 db apróra vágott hagymával, 1 db tojással, 1 evőkanál pirospaprika őrleménnyel, 1,5 teáskanál sóval és 0,5 teáskanál borssal.',
                'A tölteléket a 12 káposztalevélbe göngyöljük, a széleket behajtjuk.',
                'Egy nagy lábas aljára tesszük a vágott káposzta felét, rá a töltelékeket, 300 g szeletelt füstölt tarját és 200 g karikára vágott kolbászt, végül a maradék káposztát.',
                'Felöntjük 1500 ml vízzel, és lassú tűzön 2 órán át főzzük.',
                '300 g tejföllel tálaljuk.',
            ],
            24 => [ // Mákos guba
                '6 db száraz kiflit 1 cm-es karikákra vágunk, és egy tálba tesszük.',
                '300 ml tejet 20 g cukorral meglangyosítunk, és a kiflire öntjük.',
                'Állni hagyjuk 10 percig, amíg a kifli magába szívja a tejet.',
                '100 g darált mákot 80 g porcukorral összekeverünk, és rétegenként a kiflire szórjuk.',
                'Vaníliasodót főzünk: 3 db tojássárgáját 60 g cukorral kikeverünk, hozzáadunk 500 ml tejet és 1 teáskanál vaníliát, és folyamatos keverés mellett sűrűre melegítjük.',
                'A mákos gubát tányérokra adagoljuk, és a vaníliasodóval leöntve tálaljuk.',
            ],
            25 => [ // Zöldborsófőzelék
                '1 db hagymát apróra vágunk, és 1 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 600 g zöldborsót, felöntjük 500 ml vízzel, és 1 teáskanál sóval, 10 g cukorral ízesítjük.',
                '15 percig főzzük, amíg a borsó megpuhul.',
                '2 evőkanál olajon 30 g lisztből világos rántást készítünk, és 200 ml hideg tejjel simára keverjük.',
                'A rántást a borsóhoz keverjük, összeforraljuk, és 1 csokor apróra vágott petrezselyemmel megszórjuk.',
                '4 db virslit forró vízben 5 percig melegítünk, és a főzelékkel tálaljuk.',
            ],
            26 => [ // Csirkepaprikás
                '600 g csirkemellet megmosunk és 3 cm-es darabokra vágunk.',
                '2 db hagymát apróra vágunk, és 40 g zsíron aranysárgára pirítjuk.',
                'Levesszük a tűzről, belekeverünk 2 evőkanál pirospaprika őrleményt, és hozzáadjuk a csirkét.',
                'Hozzáadunk 2 db felszeletelt paprikát, felöntjük 300 ml vízzel, 1,5 teáskanál sóval és 0,25 teáskanál borssal fűszerezzük, és 25 percig pároljuk.',
                '250 g tejfölt 20 g liszttel simára keverünk, a szaftba keverjük, és összeforraljuk.',
                '500 g kifőzött galuskával (nokedlivel) tálaljuk.',
            ],
            27 => [ // Almás rétes
                '250 g lisztből, 150 ml langyos vízből, 1 evőkanál olajból és 0,25 teáskanál sóból rugalmas tésztát dagasztunk, és cipóba formázzuk.',
                'A cipót 1 evőkanál olajjal bekenjük, letakarva 30 percig pihentetjük, majd lisztezett abroszon hártyavékonyra nyújtjuk.',
                '6 db almát meghámozunk, lereszelünk, kinyomkodunk, és 100 g cukorral, 1 teáskanál fahéjjal és 80 g darált dióval összekeverjük.',
                'A tésztát megkenjük 30 g olvasztott vajjal, megszórjuk 40 g zsemlemorzsával, rásimítjuk a tölteléket, és az abrosz segítségével feltekerjük.',
                'Sütőpapírral bélelt tepsibe fektetjük, és a tetejét 30 g olvasztott vajjal megkenjük.',
                'Előmelegített sütőben 190°C-on 35 percig aranybarnára sütjük, és 20 g porcukorral meghintjük.',
            ],
            28 => [ // Spenótfőzelék
                '3 gerezd fokhagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 600 g (fagyasztott esetén felengedett) spenótot, és 1 teáskanál sóval, 0,25 teáskanál borssal ízesítjük.',
                'Közepes lángon, gyakran kevergetve 5 percig pároljuk.',
                '30 g lisztet 300 ml hideg tejjel csomómentesre keverünk, és a spenóthoz öntjük.',
                'Hozzáadunk 100 ml tejszínt, és addig forraljuk, amíg besűrűsödik.',
                '4 db tojást 10 perc alatt keményre főzünk, és félbevágva a főzelékre téve tálaljuk.',
            ],
            29 => [ // Bakonyi sertésborda
                '600 g sertéskarajt 4 szeletre vágunk, kiklopfolunk, és 1 teáskanál sóval, 0,5 teáskanál borssal fűszerezünk.',
                '2 evőkanál olajon a szeleteket oldalanként 2 percig elősütjük, majd tepsibe rakjuk.',
                '1 db hagymát apróra vágunk, 300 g gombát felszeletelünk, 1 evőkanál olajon együtt megpároljuk, végül megszórjuk 1 evőkanál pirospaprika őrleménnyel.',
                '200 g tejfölt 100 ml tejszínnel összekeverünk, a gombához adjuk, és a húsra öntjük.',
                'Előmelegített sütőben 180°C-on 25 percig sütjük.',
                '300 g rizst 600 ml vízben megpárolunk, és a hússal tálaljuk.',
            ],
            30 => [ // Krumplifőzelék
                '800 g burgonyát meghámozunk és 1,5 cm-es kockákra vágunk.',
                'Felöntjük 800 ml vízzel, hozzáadunk 1,5 teáskanál sót és 1 db babérlevelet, és 15 percig főzzük.',
                '2 evőkanál olajon 30 g lisztből világos rántást készítünk, és megszórjuk 1 teáskanál pirospaprika őrleménnyel.',
                'A rántást a burgonya főzőlevéből kimert 200 ml-rel simára keverjük, visszaöntjük a burgonyához, és összeforraljuk.',
                '1 evőkanál ecettel savanykásra ízesítjük.',
                '1 csokor apróra vágott petrezselyemmel megszórva tálaljuk.',
            ],
            31 => [ // Gombapörkölt
                '800 g gombát megtisztítunk és negyedekre vágunk.',
                '2 db hagymát apróra vágunk, és 3 evőkanál olajon üvegesre dinszteljük.',
                'Levesszük a tűzről, belekeverünk 2 evőkanál pirospaprika őrleményt, és hozzáadjuk a gombát.',
                'Hozzáadunk 1 db felszeletelt paprikát és 1 db paradicsomot, 1 teáskanál sóval, 0,25 teáskanál borssal ízesítjük, és felöntjük 100 ml vízzel.',
                '15 percig pároljuk, majd 200 g tejföllel dúsítjuk, és összeforraljuk.',
                '500 g kifőzött nokedlivel tálaljuk.',
            ],
            32 => [ // Túrógombóc
                '500 g túrót villával áttörünk, hogy csomómentes legyen.',
                'Összekeverjük 2 db tojással, 30 g cukorral, 100 g liszttel és 0,25 teáskanál sóval, majd 20 percig hűtőben pihentetjük.',
                'Nedves kézzel 12 db diónyi gombócot formázunk.',
                'Forrásban lévő vízben főzzük; amikor feljönnek a felszínre, még 4 percig.',
                '50 g vajon 100 g zsemlemorzsát aranybarnára pirítunk, és a lecsepegtetett gombócokat beleforgatjuk.',
                '200 g tejföllel és 40 g porcukorral megszórva tálaljuk.',
            ],
            33 => [ // Húsleves
                '1000 g marhahúst 3000 ml hideg vízben feltesszük főni.',
                'Amikor felforrt, a habot szűrőkanállal gondosan leszedjük.',
                'Hozzáadunk 3 db megtisztított sárgarépát, 1 db zellert, 1 db egész hagymát és 2 gerezd fokhagymát.',
                '2 teáskanál sóval, 1 teáskanál egész borssal és 2 db babérlevéllel ízesítjük.',
                'Lassú tűzön, gyöngyözve 3 órán át főzzük.',
                '200 g csigatésztát külön kifőzünk; a leszűrt levest a felszeletelt hússal, a zöldségekkel és a tésztával tálaljuk.',
            ],
            34 => [ // Rakott palacsinta
                '200 g lisztből, 2 db tojásból, 400 ml tejből és 0,25 teáskanál sóból palacsintatésztát keverünk, és 2 evőkanál olajjal 10 vékony palacsintát sütünk.',
                '1 db hagymát apróra vágunk, 1 evőkanál olajon megdinszteljük, hozzáadunk 500 g darált húst, és fehéredésig pirítjuk.',
                '200 ml paradicsomszósszal, 1 teáskanál sóval és 0,5 teáskanál borssal ízesítjük, és 20 percig főzzük.',
                'Egy tepsit kikenünk 10 g vajjal, és az aljára egy palacsintát fektetünk.',
                'Rétegezzük: palacsinta, húsos ragu, tejföl, reszelt sajt – összesen 300 g tejfölt és 150 g sajtot használunk fel, a tetejére sajt kerüljön.',
                'Előmelegített sütőben 180°C-on 20 percig sütjük.',
            ],
            35 => [ // Fasírt
                '800 g darált húst összekeverünk 2 db tojással, 1 db apróra vágott hagymával, 2 gerezd zúzott fokhagymával, 60 g zsemlemorzsával, 1,5 teáskanál sóval és 0,5 teáskanál borssal.',
                'Alaposan összedolgozzuk, majd vizes kézzel 12 db lapos pogácsát formázunk.',
                'Sütőpapírral bélelt tepsire sorakoztatjuk, és 2 evőkanál olajjal megkenjük.',
                'Előmelegített sütőben 180°C-on 30 percig sütjük, félidőben megfordítjuk.',
                '1200 g burgonyát meghámozunk, felkockázunk, és 1 teáskanál sóval ízesített vízben puhára főzünk.',
                'A burgonyát összetörjük 50 g vajjal és 200 ml meleg tejjel, és a fasírttal tálaljuk.',
            ],
            36 => [ // Karfiolleves
                '600 g karfiolt rózsáira szedünk és megmosunk.',
                '800 ml vízben, 1 teáskanál sóval 15 perc alatt puhára főzzük.',
                'Hozzáadunk 200 ml tejet és 100 ml tejszínt, és összeforraljuk.',
                'Belekeverünk 80 g reszelt sajtot, amíg elolvad, és 0,25 teáskanál borssal ízesítjük.',
                'Botmixerrel krémesre turmixoljuk.',
                '2 szelet kenyeret kockára vágva megpirítunk, és a levest a kenyérkockákkal és 20 g reszelt sajttal tálaljuk.',
            ],
            37 => [ // Töltött tojás
                '6 db tojást 10 perc alatt keményre főzünk, majd hideg vízben lehűtjük.',
                'Meghámozzuk, hosszában félbevágjuk, és a sárgájukat egy tálba kaparjuk.',
                'A sárgáját villával összetörjük, és 3 evőkanál majonézzel, 1 teáskanál mustárral, 0,25 teáskanál sóval és 0,25 teáskanál borssal simára keverjük.',
                'A krémet habzsákba töltjük, és visszanyomjuk a tojásfehérjékbe.',
                '0,5 teáskanál pirospaprika őrleménnyel és 0,5 csokor apróra vágott petrezselyemmel megszórva tálaljuk.',
            ],
            38 => [ // Sólet
                '500 g szárazbabot előző este bő hideg vízbe áztatunk.',
                '2 db hagymát apróra vágunk, 3 evőkanál olajon megdinszteljük, és hozzáadunk 3 gerezd zúzott fokhagymát.',
                'Megszórjuk 1 evőkanál pirospaprika őrleménnyel és 20 g liszttel, majd hozzáadjuk a leszűrt babot és 600 g egészben hagyott marhahúst.',
                '2 teáskanál sóval és 0,5 teáskanál borssal fűszerezzük, és felöntjük 2500 ml vízzel.',
                '6 db tojást héjastul a bab közé teszünk, lefedjük, és 160°C-os sütőben 2,5 órán át sütjük.',
                'A húst felszeleteljük, a tojásokat meghámozzuk, és a babbal együtt tálaljuk.',
            ],
            39 => [ // Gyümölcsleves
                '2 db almát meghámozunk és felkockázunk, 200 g epret negyedelünk, 200 g meggyet kimagozunk.',
                '1000 ml vizet 100 g cukorral és 0,5 teáskanál fahéjjal felforralunk, beletesszük a gyümölcsöket, és 10 percig főzzük.',
                '2 evőkanál keményítőt 200 ml tejszínnel simára keverünk.',
                'A tejszínes keveréket a leveshez öntjük, és folyamatos keverés mellett összeforraljuk.',
                'Lehűtjük, és legalább 2 órára hűtőbe téve hidegen tálaljuk.',
            ],
            40 => [ // Puliszka
                '1000 ml vizet 1 teáskanál sóval felforralunk.',
                'Folyamatos keverés mellett vékony sugárban beleszórunk 250 g kukoricadarát.',
                'Alacsony lángon, gyakran kevergetve 20 percig főzzük, amíg elválik a lábas falától, majd belekeverünk 30 g vajat.',
                'Tányérokra adagoljuk, és megkenjük 200 g tejföllel.',
                '150 g reszelt sajttal megszórva, forrón tálaljuk.',
            ],
            41 => [ // Sertésszelet paradicsommal
                '600 g sertéskarajt 4 szeletre vágunk, kiklopfolunk, és 1 teáskanál sóval, 0,25 teáskanál borssal fűszerezünk.',
                '2 evőkanál olajon a szeleteket oldalanként 3 percig elősütjük.',
                'Tepsibe fektetjük, és a tetejükre 3 db felkarikázott paradicsomot rakunk.',
                'Megszórjuk 1 teáskanál szárított bazsalikommal és 150 g reszelt sajttal.',
                'Előmelegített sütőben 200°C-on 15 percig sütjük, amíg a sajt aranybarnára pirul, és melegen tálaljuk.',
            ],
            42 => [ // Babgulyás
                '400 g szárazbabot előző este hideg vízbe áztatunk.',
                'Másnap a leszűrt babot és 800 g füstölt csülköt 3000 ml vízben, 2 db babérlevéllel feltesszük főni.',
                '2 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, hozzáadunk 3 gerezd zúzott fokhagymát és 2 evőkanál pirospaprika őrleményt, és a leveshez keverjük.',
                '1,5 óra főzés után hozzáadunk 2 db karikára vágott sárgarépát, 400 g felkockázott burgonyát, 1 db paprikát és 1 db paradicsomot.',
                '1 teáskanál sóval és 0,5 teáskanál borssal ízesítjük, és további 30 percig főzzük.',
                'A csülköt kivesszük, lecsontozzuk, feldaraboljuk, visszatesszük a levesbe, és melegen tálaljuk.',
            ],
            43 => [ // Kakaós csiga
                '25 g élesztőt 250 ml langyos tejben 10 g cukorral felfuttatunk.',
                '500 g lisztet összekeverünk 40 g cukorral, 0,5 teáskanál sóval, 1 db tojással, 80 g olvasztott vajjal és a felfutott élesztővel, sima tésztává dagasztjuk, és 1 órán át kelesztjük.',
                'A megkelt tésztát 40×30 cm-es téglalappá nyújtjuk, és megkenjük 50 g olvasztott vajjal.',
                'Megszórjuk 40 g kakaópor és 100 g cukor keverékével, szorosan feltekerjük, és 16 szeletre vágjuk.',
                'Sütőpapírral bélelt tepsibe rakjuk, 20 percig kelesztjük, 1 db felvert tojással megkenjük, és 180°C-on 25 percig sütjük.',
                '100 g porcukrot 30 ml tejjel sűrű mázzá keverünk, és a langyos csigákra csorgatjuk.',
            ],
            44 => [ // Savanyú krumplileves
                '600 g burgonyát meghámozunk és felkockázunk.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, majd megszórjuk 20 g liszttel és 1 evőkanál pirospaprika őrleménnyel.',
                'Felöntjük 1500 ml vízzel, hozzáadjuk a burgonyát, 200 g felkockázott füstölt tarját és 2 db babérlevelet.',
                '1 teáskanál sóval, 0,25 teáskanál borssal és 2 evőkanál ecettel ízesítjük, és 20 percig főzzük.',
                'Hozzáadunk 150 g felkarikázott kolbászt, és további 5 percig főzzük.',
                '150 g tejföllel behabarjuk, összeforraljuk, és tálaljuk.',
            ],
            45 => [ // Rántott csirkemell
                '600 g csirkemellet 8 vékony szeletre vágunk, kiklopfolunk, és 1 teáskanál sóval, 0,25 teáskanál borssal fűszerezünk.',
                '2 db tojást felverünk; 80 g lisztet és 150 g zsemlemorzsát külön tányérra szórunk.',
                'A szeleteket lisztbe, tojásba, majd zsemlemorzsába forgatjuk.',
                '400 ml olajat felforrósítunk, és a húsokat oldalanként 3 percig aranybarnára sütjük.',
                'Papírtörlőn lecsöpögtetjük, és 1 db citrom karikáival és 1 fej salátával tálaljuk.',
            ],
            46 => [ // Brokkoli krémleves
                '500 g brokkolit rózsáira szedünk, a torzsáját felkockázzuk.',
                '1 db hagymát apróra vágunk, és 20 g vajon megdinszteljük.',
                'Hozzáadjuk a brokkolit, felöntjük 700 ml vízzel, 1 teáskanál sóval ízesítjük, és 12 percig főzzük.',
                'Hozzáadunk 200 ml tejet és 100 ml tejszínt, és belekeverünk 60 g reszelt sajtot.',
                'Botmixerrel krémesre turmixoljuk, és 0,25 teáskanál borssal ízesítjük.',
                '20 g reszelt sajttal megszórva tálaljuk.',
            ],
            47 => [ // Tarhonyás hús
                '300 g tarhonyát 1 evőkanál olajon, folyamatosan kevergetve aranybarnára pirítunk.',
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 500 g felkockázott sertéshúst, megszórjuk 1 evőkanál pirospaprika őrleménnyel, és fehéredésig pirítjuk.',
                'Hozzáadunk 1 db felszeletelt paprikát és 1 db paradicsomot, 1,5 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, felöntjük 300 ml vízzel, és 30 percig pároljuk.',
                'Belekeverjük a pirított tarhonyát, és felöntjük további 500 ml vízzel.',
                'Lefedve, lassú tűzön 20 percig pároljuk, amíg a tarhonya megszívja magát.',
            ],
            48 => [ // Madártej
                '1000 ml tejet 1 teáskanál vaníliával feltesszük forrni.',
                '6 db tojás fehérjét 0,25 teáskanál sóval és 50 g cukorral kemény habbá verjük.',
                'Evőkanállal galuskákat szaggatunk a gyöngyöző tejbe, oldalanként 1 percig főzzük, majd kiszedjük.',
                'A 6 tojássárgáját 100 g cukorral habosra keverjük, és folyamatos keverés mellett vékony sugárban hozzáöntjük a forró tejet.',
                'Visszaöntjük a lábasba, és alacsony lángon sűrűsödésig melegítjük (nem forraljuk!).',
                'A sodót tálba öntjük, a habgaluskákat a tetejére helyezzük, és hidegen tálaljuk.',
            ],
            49 => [ // Csülkös bableves
                '400 g szárazbabot előző este hideg vízbe áztatunk.',
                'Másnap a leszűrt babot és 1000 g füstölt csülköt 3000 ml vízben, 2 db babérlevéllel feltesszük főni, és 1,5 órán át főzzük.',
                'Hozzáadunk 2 db karikára vágott sárgarépát, 1 teáskanál sót és 0,5 teáskanál borsot.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, 2 gerezd fokhagymával, 20 g liszttel és 1 evőkanál pirospaprika őrleménnyel rántást készítünk, és a leveshez keverjük.',
                'Hozzáadunk 200 g felkarikázott kolbászt, és további 20 percig főzzük.',
                'A csülköt lecsontozzuk, feldaraboljuk, visszatesszük, és 150 g tejföllel tálaljuk.',
            ],
            50 => [ // Lecsó
                '2 db hagymát karikára vágunk, és 2 evőkanál olajon megdinszteljük.',
                '150 g kolbászt felkarikázunk, és a hagymával 2 percig pirítjuk.',
                'Hozzáadunk 6 db felkarikázott paprikát, és 5 percig pároljuk.',
                'Hozzáadunk 4 db felkockázott paradicsomot, 1 teáskanál sóval és 1 teáskanál pirospaprika őrleménnyel ízesítjük, és 10 percig főzzük.',
                '4 db tojást felverünk, a lecsóba öntjük, kevergetve addig sütjük, amíg megszilárdul, és melegen tálaljuk.',
            ],
            51 => [ // Burgonyafőzelék
                '800 g burgonyát meghámozunk és felkockázunk.',
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a burgonyát, felöntjük 700 ml vízzel, 1,5 teáskanál sóval ízesítjük, és 15 percig főzzük.',
                '150 g tejfölt 30 g liszttel és 1 teáskanál pirospaprika őrleménnyel simára keverünk, és a burgonyához adjuk.',
                'Összeforraljuk, és a burgonya egy részét a lábas falához nyomkodjuk, hogy sűrűbb legyen.',
                '1 csokor apróra vágott petrezselyemmel megszórva tálaljuk.',
            ],
            52 => [ // Csirkemell rolád
                '600 g csirkemellet 4 szeletre vágunk, vékonyra klopfolunk, és 1 teáskanál sóval, 0,25 teáskanál borssal fűszerezünk.',
                'Minden szeletre 30 g sonkát és 30 g sajtot fektetünk (összesen 120 g sonka és 120 g sajt).',
                'Szorosan feltekerjük, és fogpiszkálóval rögzítjük.',
                '2 evőkanál olajon körbepirítjuk a roládokat.',
                'Előmelegített sütőben 180°C-on 20 percig sütjük.',
                '250 g rizst 500 ml vízben megpárolunk, és a felszeletelt roládokkal tálaljuk.',
            ],
            53 => [ // Paradicsomos csirkemell
                '600 g csirkemellet 4 szeletre vágunk, 1 teáskanál sóval és 0,25 teáskanál borssal fűszerezünk, és 2 evőkanál olajon oldalanként 3 percig sütjük.',
                'A húst tepsibe fektetjük.',
                '300 ml paradicsomszószt 1 teáskanál szárított bazsalikommal elkeverünk, és a húsra öntjük.',
                '2 db paradicsomot felkarikázunk, és a húsra rakjuk.',
                'Megszórjuk 150 g reszelt sajttal.',
                'Előmelegített sütőben 200°C-on 20 percig sütjük, amíg a sajt aranybarnára pirul.',
            ],
            54 => [ // Sütőtök krémleves
                '800 g sütőtököt meghámozunk, kimagozunk és felkockázunk.',
                'Tepsibe terítjük, 1 evőkanál olajjal meglocsoljuk, és 200°C-on 30 percig sütjük.',
                '1 db hagymát apróra vágunk, 1 evőkanál olajon megdinszteljük, hozzáadjuk a sült tököt, és felöntjük 500 ml vízzel és 200 ml tejjel.',
                '1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, 10 percig főzzük, majd 100 ml tejszínnel krémesre turmixoljuk.',
                '40 g tökmagot száraz serpenyőben megpirítunk.',
                'A levest a pirított tökmaggal megszórva tálaljuk.',
            ],
            55 => [ // Rizses hús
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 500 g felkockázott sertéshúst, megszórjuk 1 evőkanál pirospaprika őrleménnyel, és fehéredésig pirítjuk.',
                'Hozzáadunk 1 db felszeletelt paprikát, 1,5 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, felöntjük 300 ml vízzel, és 30 percig pároljuk.',
                'Belekeverünk 250 g átmosott rizst és 150 g zöldborsót, majd felöntjük további 500 ml vízzel.',
                'Lefedve, lassú tűzön 20 percig pároljuk, amíg a rizs megszívja a vizet, és melegen tálaljuk.',
            ],
            56 => [ // Málnás muffin
                '250 g lisztet, 150 g cukrot, 2 teáskanál sütőport és 0,25 teáskanál sót összekeverünk.',
                'Egy másik tálban 2 db tojást, 200 ml tejet és 100 g olvasztott vajat simára keverünk, majd a száraz hozzávalókhoz öntjük, és épp csak összekeverjük.',
                '200 g málnát óvatosan a tésztába forgatunk.',
                'A tésztát 12 muffinpapírral bélelt formába adagoljuk.',
                'Előmelegített sütőben 180°C-on 20 percig sütjük, majd rácson kihűtjük.',
                '20 g porcukorral meghintve tálaljuk.',
            ],
            57 => [ // Sárgaborsó főzelék
                '400 g sárgaborsót előző este hideg vízbe áztatunk.',
                'Másnap leszűrjük, és 1200 ml friss vízben, 1 db babérlevéllel feltesszük főni.',
                '1,5 teáskanál sóval ízesítjük, 40 perc alatt puhára főzzük, majd botmixerrel pürésítjük.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon 2 gerezd zúzott fokhagymával megdinszteljük, és a főzelékhez keverjük.',
                '200 g kolbászt felkarikázunk, és serpenyőben átpirítjuk.',
                'A főzeléket a pirított kolbásszal tálaljuk.',
            ],
            58 => [ // Csokis brownie
                '200 g csokoládét és 150 g vajat vízgőz felett megolvasztunk, majd langyosra hűtjük.',
                'Belekeverünk 200 g cukrot, majd egyenként 3 db tojást.',
                '100 g lisztet, 20 g kakaóport és 0,25 teáskanál sót a masszához szitálunk, és simára keverjük.',
                '100 g diót durvára vágunk, és a tésztába forgatjuk.',
                '20×20 cm-es, sütőpapírral bélelt formába öntjük, és 180°C-on 25 percig sütjük (a közepe maradjon kissé nedves).',
                'Kihűlés után 9 kockára vágva tálaljuk.',
            ],
            59 => [ // Kolbászos lecsós tészta
                '400 g tésztát bő vízben kifőzünk, és leszűrünk.',
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 200 g felkarikázott kolbászt, és 3 percig pirítjuk.',
                'Hozzáadunk 4 db felkarikázott paprikát és 3 db felkockázott paradicsomot, és 10 percig pároljuk.',
                '1 teáskanál sóval, 0,25 teáskanál borssal és 1 teáskanál pirospaprika őrleménnyel ízesítjük.',
                'A tésztát összekeverjük a kolbászos lecsóval, és azonnal tálaljuk.',
            ],
            60 => [ // Zabkása
                '100 g zabpelyhet egy lábasba teszünk, és felöntjük 400 ml tejjel.',
                'Közepes lángon, folyamatosan kevergetve 5 percig főzzük, amíg besűrűsödik.',
                '2 evőkanál mézzel édesítjük.',
                '1 db banánt felkarikázunk, 100 g epret negyedelünk, 30 g diót durvára vágunk.',
                'A kását tálkákba szedjük, és a gyümölccsel és a dióval megszórva, melegen tálaljuk.',
            ],
            61 => [ // Sertésragu leves
                '500 g sertéshúst megmosunk és 1,5 cm-es kockákra vágunk.',
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a húst, fehéredésig pirítjuk, majd felöntjük 2000 ml vízzel, és 2 teáskanál sóval, 0,5 teáskanál borssal és 2 db babérlevéllel ízesítjük.',
                '40 perc főzés után hozzáadunk 2 db karikára vágott sárgarépát, 400 g felkockázott burgonyát és 150 g zöldborsót, és további 20 percig főzzük.',
                '200 g tejfölt 20 g liszttel simára keverünk, a levesbe habarjuk, és összeforraljuk.',
                '1 csokor apróra vágott petrezselyemmel megszórva tálaljuk.',
            ],
            62 => [ // Csirkés Caesar saláta
                '300 g csirkemellet 0,5 teáskanál sóval, 0,25 teáskanál borssal és 1 evőkanál olajjal bedörzsölünk, és grillserpenyőben oldalanként 5 percig sütjük.',
                '1 fej római salátát megmosunk, és nagyobb darabokra tépkedünk.',
                '2 szelet kenyeret kockákra vágunk, és 1 evőkanál olajon ropogósra pirítjuk (ez lesz a kruton).',
                'Az öntethez 3 evőkanál majonézt, 0,5 db citrom levét, 1 gerezd zúzott fokhagymát és 1 teáskanál mustárt simára keverünk.',
                'A salátát összeforgatjuk az öntettel, ráfektetjük a felszeletelt csirkét és a krutont.',
                '40 g parmezánforgáccsal megszórva tálaljuk.',
            ],
            63 => [ // Rakott cukkini
                '1000 g cukkinit megmosunk, karikákra vágunk, 0,5 teáskanál sóval megszórjuk, és 10 perc után leitatjuk.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, hozzáadunk 500 g darált húst, és fehéredésig pirítjuk.',
                '300 ml paradicsomszósszal, 1 teáskanál sóval és 0,5 teáskanál borssal ízesítjük, és 15 percig főzzük.',
                'Egy tepsit kikenünk 1 evőkanál olajjal, és rétegezzük a cukkinit és a húsos ragut, amíg a hozzávalók el nem fogynak.',
                'A tetejét megkenjük 200 g tejföllel, és megszórjuk 150 g reszelt sajttal.',
                'Előmelegített sütőben 180°C-on 30 percig sütjük.',
            ],
            64 => [ // Tárkonyos csirkeraguleves
                '400 g csirkemellet megmosunk és kis kockákra vágunk.',
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a csirkét, 1,5 teáskanál sóval, 0,25 teáskanál borssal és 1 teáskanál szárított tárkonnyal fűszerezzük, és fehéredésig pirítjuk.',
                'Hozzáadunk 2 db karikára vágott sárgarépát és 100 g zöldborsót, majd felöntjük 1500 ml vízzel.',
                '25 percig főzzük, amíg a zöldségek megpuhulnak.',
                '200 g tejfölt 20 g liszttel simára keverünk, a levesbe habarjuk, összeforraljuk, és tálaljuk.',
            ],
            65 => [ // Görög saláta
                '4 db paradicsomot, 1 db uborkát és 1 db paprikát megmosunk, és nagyobb kockákra vágunk.',
                '1 db lilahagymát vékony karikákra vágunk.',
                'A zöldségeket egy tálban összekeverjük 80 g olívabogyóval.',
                '3 evőkanál olívaolajjal meglocsoljuk, és 0,5 teáskanál sóval, 0,25 teáskanál borssal ízesítjük.',
                'A tetejére 200 g felkockázott feta sajtot szórunk, óvatosan átforgatjuk, és azonnal tálaljuk.',
            ],
            66 => [ // Burgonyás pogácsa
                '250 g burgonyát héjában megfőzünk, meghámozzuk, és még melegen áttörjük.',
                '20 g élesztőt 100 ml langyos tejben 5 g cukorral felfuttatunk.',
                '500 g lisztet összegyúrunk a burgonyával, 150 g vajjal, 1 db tojással, 2 teáskanál sóval és az élesztővel, majd 1 órán át kelesztjük.',
                '2 cm vastagra nyújtjuk, pogácsaszaggatóval kiszaggatjuk, és sütőpapírral bélelt tepsibe rakjuk.',
                'A tetejüket 1 db felvert tojással megkenjük, és megszórjuk 100 g reszelt sajttal.',
                'Előmelegített sütőben 200°C-on 20 percig aranybarnára sütjük.',
            ],
            67 => [ // Spenótos-tejfölös tészta
                '400 g penne tésztát bő vízben kifőzünk, és leszűrünk.',
                '3 gerezd fokhagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 300 g spenótot, 1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és 3 percig pároljuk.',
                'Belekeverünk 200 ml tejszínt és 150 g tejfölt, és összeforraljuk.',
                'A tésztát összekeverjük a spenótos mártással.',
                '80 g reszelt sajttal megszórva, azonnal tálaljuk.',
            ],
            68 => [ // Céklaleves
                '600 g céklát meghámozunk és felkockázunk.',
                '1 db hagymát apróra vágunk, és 1 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a céklát, felöntjük 800 ml vízzel, 1 teáskanál sóval és 1 evőkanál ecettel ízesítjük, és 30 perc alatt puhára főzzük.',
                'Hozzáadunk 100 ml tejszínt, és botmixerrel krémesre turmixoljuk.',
                'Tányérokba merjük, és 100 g tejföllel a tetején tálaljuk.',
            ],
            69 => [ // Mártásos csirkemell
                '600 g csirkemellet 4 szeletre vágunk, 1 teáskanál sóval és 0,25 teáskanál borssal fűszerezünk, és 2 evőkanál olajon oldalanként 4 percig sütjük.',
                '1 db hagymát apróra vágunk, 300 g gombát felszeletelünk, és 1 evőkanál olajon 8 percig pároljuk.',
                '200 ml tejszínt öntünk a gombához, és 3 perc alatt sűrűre főzzük.',
                'A csirkét visszatesszük a mártásba, és átforgatjuk.',
                '400 g tésztát kifőzünk, és a mártásos csirkével tálaljuk.',
            ],
            70 => [ // Diós kalács
                '25 g élesztőt 250 ml langyos tejben 10 g cukorral felfuttatunk.',
                '500 g lisztet 70 g cukorral, 0,5 teáskanál sóval, 1 db tojással, 100 g olvasztott vajjal és az élesztővel sima tésztává dagasztunk.',
                'Letakarva 1 órán át, a duplájára kelesztjük.',
                '250 g darált diót 150 g cukorral és 100 ml forró tejjel kenhető töltelékké keverünk; a tésztát téglalappá nyújtjuk, megkenjük vele, és szorosan feltekerjük.',
                'Kalácsformába fektetjük, 30 percig kelesztjük, és 1 db felvert tojással megkenjük.',
                'Előmelegített sütőben 180°C-on 40 percig aranybarnára sütjük.',
            ],
            71 => [ // Zöldséges csirke stir fry
                '500 g csirkemellet vékony csíkokra vágunk, és 2 evőkanál szójaszósszal és 1 evőkanál keményítővel összeforgatjuk.',
                '2 db paprikát csíkokra, 2 db sárgarépát vékony hasábokra, 1 db hagymát félkarikákra vágunk, 300 g brokkolit rózsáira szedünk.',
                '300 g rizst 600 ml vízben megpárolunk.',
                'Wokban 3 evőkanál olajat forrósítunk, a csirkét magas hőfokon 4 percig pirítjuk, majd kiszedjük.',
                'A wokba tesszük a zöldségeket, 2 gerezd zúzott fokhagymát és 20 g reszelt gyömbért, és kevergetve 4 percig pirítjuk.',
                'Visszatesszük a csirkét, 2 evőkanál szójaszósszal ízesítjük, és a rizzsel, 40 g pirított földimogyoróval megszórva azonnal tálaljuk.',
            ],
            72 => [ // Paradicsomos bab
                '300 g szárazbabot előző este hideg vízbe áztatunk.',
                'Másnap leszűrjük, 1500 ml friss vízben 1 óra alatt puhára főzzük, majd leszűrjük.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, és hozzáadunk 2 gerezd zúzott fokhagymát.',
                'Hozzáadunk 150 g felkarikázott kolbászt, és 2 percig pirítjuk.',
                'Hozzáadjuk a babot és 400 ml paradicsomszószt, és 1 teáskanál sóval, 0,25 teáskanál borssal, 1 teáskanál pirospaprika őrleménnyel és 10 g cukorral ízesítjük.',
                '15 percig főzzük, hogy az ízek összeérjenek, és melegen tálaljuk.',
            ],
            73 => [ // Sajtos-tejfölös melegszendvics
                '150 g tejfölt összekeverünk 100 g reszelt sajttal, 1 gerezd zúzott fokhagymával, 0,25 teáskanál sóval és 0,25 teáskanál borssal.',
                '4 szelet kenyeret sütőpapírral bélelt tepsire fektetünk.',
                'A sajtos-tejfölös krémet vastagon a kenyérszeletekre kenjük.',
                'Előmelegített sütőben 200°C-on 10 percig sütjük, amíg a teteje aranybarnára pirul, és forrón tálaljuk.',
            ],
            74 => [ // Zöldségkrémleves
                '3 db sárgarépát, 300 g burgonyát és 1 db zellert meghámozunk és felkockázunk.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, és hozzáadjuk a zöldségeket.',
                'Felöntjük 1000 ml vízzel, 1,5 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és 25 percig főzzük.',
                'Hozzáadunk 100 ml tejszínt, és botmixerrel krémesre turmixoljuk.',
                '2 szelet kenyeret kockára vágunk, és száraz serpenyőben megpirítjuk.',
                'A levest a kenyérkockákkal megszórva tálaljuk.',
            ],
            75 => [ // Csirkés wrap
                '250 g csirkemellet vékony csíkokra vágunk, 0,5 teáskanál sóval, 0,25 teáskanál borssal és 0,5 teáskanál pirospaprika őrleménnyel fűszerezzük, és 1 evőkanál olajon 6 percig sütjük.',
                '2 db tortillát száraz serpenyőben oldalanként 20 másodpercig melegítünk.',
                '0,5 fej salátát megmosunk és csíkokra vágunk, 1 db paradicsomot és 1 db paprikát felkockázunk.',
                '100 g joghurtot 1 gerezd zúzott fokhagymával öntetté keverünk.',
                'A tortillákra salátát, zöldségeket és csirkét halmozunk, meglocsoljuk az öntettel, és szorosan feltekerjük.',
                'Félbevágva, azonnal tálaljuk.',
            ],
            76 => [ // Krumplis tészta
                '600 g burgonyát meghámozunk és apró kockákra vágunk.',
                '1 db hagymát apróra vágunk, és 3 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a burgonyát, megszórjuk 1 teáskanál pirospaprika őrleménnyel, és gyakran kevergetve pirítjuk.',
                '1,5 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és fedő alatt 15 perc alatt puhára sütjük.',
                '400 g kockatésztát bő vízben kifőzünk, és leszűrünk.',
                'A tésztát összekeverjük a pirított burgonyával, és azonnal tálaljuk.',
            ],
            77 => [ // Csokoládé torta
                '100 g csokoládét és 100 g vajat vízgőz felett megolvasztunk.',
                '4 db tojást 200 g cukorral habosra keverünk, és hozzáadjuk az olvasztott csokoládét.',
                '150 g lisztet, 30 g kakaóport és 1 teáskanál sütőport a masszához szitálunk, és simára keverjük.',
                'Sütőpapírral bélelt, 24 cm-es tortaformába öntjük.',
                'Előmelegített sütőben 180°C-on 35 percig sütjük, majd kihűtjük.',
                '200 ml tejszínt felforralunk, 100 g csokoládét és 50 g vajat olvasztunk benne, a krémmel bevonjuk a tortát, és szeletelve tálaljuk.',
            ],
            78 => [ // Zöldséges lasagne
                '1 db hagymát és 2 gerezd fokhagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 400 g felkockázott cukkinit és 2 db felkockázott paprikát, és 5 percig pároljuk.',
                'Felöntjük 700 ml paradicsomszósszal, 1,5 teáskanál sóval, 0,5 teáskanál borssal és 1 teáskanál bazsalikommal ízesítjük, és 15 percig főzzük.',
                'A 250 g lasagne tésztát három részre osztjuk. Egy tepsi aljára vékony réteg ragut kenünk, rá a lasagne lapok egyharmadát, a 250 g ricotta egyharmadát és 50 g reszelt sajtot.',
                'A ragu – lasagne lap – ricotta – sajt rétegezést még kétszer megismételjük (ez további 100 g sajt), végül a tetejére a maradék ragut és az utolsó 50 g sajtot tesszük.',
                'Alufóliával lefedve 180°C-on 30 percig, majd fólia nélkül 10 percig sütjük.',
            ],
            79 => [ // Chilis bab
                '250 g szárazbabot előző este beáztatunk, majd 1500 ml friss vízben 1 óra alatt puhára főzzük, és leszűrjük.',
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 400 g darált húst és 2 gerezd zúzott fokhagymát, és fehéredésig pirítjuk.',
                'Hozzáadjuk a babot, 1 db felkockázott paprikát és 400 ml paradicsomszószt, és 1 teáskanál sóval, 0,25 teáskanál borssal, 1 teáskanál chilivel fűszerezzük.',
                'Lassú tűzön 25 percig főzzük, hogy az ízek összeérjenek.',
                '250 g rizst 500 ml vízben megpárolunk, és a chilis babbal tálaljuk.',
            ],
            80 => [ // Túrós palacsinta
                '200 g lisztből, 2 db tojásból, 400 ml tejből, 20 g cukorból és 0,25 teáskanál sóból palacsintatésztát keverünk, és 2 evőkanál olajjal 10 vékony palacsintát sütünk.',
                '500 g túrót áttörünk, és 60 g cukorral, 1 csomag vaníliás cukorral, 1 db tojással és 50 g tejföllel krémesre keverjük.',
                'A palacsintákat megtöltjük a túrós krémmel, és feltekerjük.',
                'Tepsibe fektetjük, és meglocsoljuk 150 g tejföllel.',
                'Előmelegített sütőben 180°C-on 15 percig sütjük.',
                '20 g porcukorral meghintve tálaljuk.',
            ],
            81 => [ // Borsos tokány
                '600 g sertéshúst ujjnyi vastag csíkokra vágunk.',
                '2 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a húst, fehéredésig pirítjuk, majd megszórjuk 1 teáskanál frissen őrölt borssal és 1 teáskanál sóval.',
                'Felöntjük 200 ml vízzel, és fedő alatt 35 percig pároljuk.',
                'Hozzáöntünk 200 ml tejszínt, és 5 perc alatt sűrűre főzzük.',
                '250 g rizst 500 ml vízben megpárolunk, és a tokánnyal tálaljuk.',
            ],
            82 => [ // Sütőben sült csirkecomb
                '1200 g csirkecombot megmosunk, és papírtörlővel szárazra törlünk.',
                '3 evőkanál olajat összekeverünk 1 teáskanál sóval, 0,5 teáskanál borssal, 1 teáskanál pirospaprika őrleménnyel és 3 gerezd zúzott fokhagymával.',
                '800 g burgonyát meghámozunk, cikkekre vágunk, 0,5 teáskanál sóval megszórjuk, és tepsibe terítjük.',
                'A combokat bekenjük a fűszeres olajjal, és a burgonyára fektetjük.',
                'Előmelegített sütőben 200°C-on 45 percig ropogósra sütjük.',
                '1 db citrom cikkeivel tálaljuk.',
            ],
            83 => [ // Karfiol gratin
                '800 g karfiolt rózsáira szedünk, 1500 ml vízben, 1 teáskanál sóval 5 percig előfőzzük, majd lecsepegtetjük.',
                '30 g vajat felolvasztunk, 30 g lisztet 1 percig pirítunk benne, majd 400 ml tejjel csomómentesre keverjük.',
                '100 ml tejszínnel, 0,5 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és belekeverünk 100 g reszelt sajtot.',
                'A karfiolt tepsibe terítjük, és leöntjük a sajtos mártással.',
                'Megszórjuk 50 g reszelt sajttal, és előmelegített sütőben 200°C-on 20 percig aranybarnára sütjük.',
            ],
            84 => [ // Burgonyaleves
                '700 g burgonyát meghámozunk és felkockázunk.',
                '1 db hagymát apróra vágunk, és 1 evőkanál olajon megdinszteljük.',
                'Hozzáadjuk a burgonyát, felöntjük 800 ml vízzel és 200 ml tejjel, 1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és 20 percig főzzük.',
                'Hozzáadunk 100 ml tejszínt, és botmixerrel krémesre turmixoljuk.',
                '100 g szalonnát apró kockákra vágunk, és serpenyőben ropogósra sütjük.',
                'A levest a szalonnapörccel megszórva tálaljuk.',
            ],
            85 => [ // Töltött cukkini
                '4 db cukkinit megmosunk, hosszában félbevágunk, és a belsejét kanállal kivájjuk.',
                '1 db hagymát apróra vágunk, és 1 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 400 g darált húst és az apróra vágott cukkinibelet, fehéredésig pirítjuk, majd 200 ml paradicsomszósszal, 1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük.',
                'A cukkinifeleket megtöltjük a húsos töltelékkel, és tepsibe sorakoztatjuk.',
                'Megszórjuk 100 g reszelt sajttal.',
                'Előmelegített sütőben 180°C-on 30 percig sütjük.',
            ],
            86 => [ // Gyros tál
                '600 g csirkemellet vékony csíkokra vágunk, és 2 evőkanál olajjal, 2 gerezd zúzott fokhagymával, 1 teáskanál pirospaprika őrleménnyel, 1 teáskanál sóval és 0,5 teáskanál borssal 1 órán át pácoljuk.',
                '1 evőkanál olajon, magas hőfokon 8 percig pirosra sütjük.',
                'A tzatzikihez 1 db uborkát lereszelünk, kinyomkodunk, és 250 g joghurttal és 1 gerezd zúzott fokhagymával összekeverjük.',
                '2 db paradicsomot felkockázunk, 1 db hagymát vékony karikákra vágunk, 0,5 fej salátát csíkokra vágunk.',
                '4 db pitát száraz serpenyőben átmelegítünk.',
                'A tányérokra pitát, zöldséget és húst halmozunk, és a tzatzikivel meglocsolva tálaljuk.',
            ],
            87 => [ // Vanília puding
                '450 ml tejet 80 g cukorral és 1 teáskanál vaníliával feltesszük forrni.',
                '3 evőkanál keményítőt 50 ml hideg tejjel simára keverünk.',
                'A forró tejhez öntjük a keményítős keveréket, folyamatos kevergetés mellett.',
                'Alacsony lángon 2-3 percig sűrűre főzzük.',
                '4 pohárba adagoljuk, és hűtőben legalább 2 órán át hűtjük.',
                '200 ml tejszínt kemény habbá verünk, és 100 g eperrel együtt a pudingra halmozva tálaljuk.',
            ],
            88 => [ // Csirkés quesadilla
                '250 g csirkemellet vékony csíkokra vágunk, 0,5 teáskanál sóval, 0,25 teáskanál borssal és 0,5 teáskanál pirospaprika őrleménnyel fűszerezzük, és 1 evőkanál olajon 6 percig sütjük.',
                '1 db paprikát vékony csíkokra vágunk.',
                '4 db tortilla egyik felére összesen 150 g reszelt sajtot szórunk.',
                'A sajtra halmozzuk a csirkét és a paprikát, majd a tortillákat félbehajtjuk.',
                'Száraz serpenyőben oldalanként 2 percig sütjük, amíg a sajt megolvad.',
                '1 db paradicsomot felkockázunk, és a cikkekre vágott quesadilla mellé tálaljuk.',
            ],
            89 => [ // Paradicsomos tészta
                '3 gerezd fokhagymát vékonyra szeletelünk, és 3 evőkanál olajon, alacsony lángon megdinszteljük.',
                'Hozzáadunk 500 ml paradicsomszószt, és 1 teáskanál sóval, 0,25 teáskanál borssal, 5 g cukorral és 1 teáskanál bazsalikommal ízesítjük.',
                'Lassú tűzön 15 percig összeforraljuk.',
                '400 g tésztát bő vízben kifőzünk, és leszűrünk.',
                'A tésztát összekeverjük a mártással.',
                '60 g reszelt sajttal megszórva tálaljuk.',
            ],
            90 => [ // Diós sütemény
                '300 g lisztet 200 g hideg vajjal elmorzsolunk.',
                'Hozzáadunk 100 g cukrot, 1 csomag vaníliás cukrot, 1 db tojást és 150 g darált diót, és omlós tésztává gyúrjuk.',
                '30 percig hűtőben pihentetjük, majd 5 mm vastagra nyújtjuk, és pogácsaszaggatóval kiszaggatjuk.',
                'Sütőpapírral bélelt tepsibe rakjuk.',
                'Előmelegített sütőben 180°C-on 12 percig világosra sütjük.',
                'Még melegen 50 g porcukorba forgatjuk, és kihűtve tálaljuk.',
            ],
            91 => [ // Sertésszűz pecsenye
                '700 g sertésszűzt megtisztítunk a hártyáktól, és papírtörlővel szárazra törlünk.',
                '1 teáskanál sóval, 0,5 teáskanál borssal és 2 gerezd zúzott fokhagymával bedörzsöljük.',
                '2 evőkanál olajon körbepirítjuk, hogy kérget kapjon.',
                '800 g burgonyát cikkekre vágunk, 1 evőkanál olajjal és 0,5 teáskanál sóval tepsibe terítjük, és ráfektetjük a húst.',
                'Előmelegített sütőben 200°C-on 25 percig sütjük.',
                'A húst 10 percig pihentetjük, felszeleteljük, és a burgonyával tálaljuk.',
            ],
            92 => [ // Zöldborsós rizs
                '1 db hagymát apróra vágunk, és 2 evőkanál olajon megdinszteljük.',
                'Hozzáadunk 300 g rizst, és üvegesre pirítjuk.',
                'Felöntjük 600 ml vízzel, és 1 teáskanál sóval ízesítjük.',
                'Hozzáadunk 200 g zöldborsót.',
                'Lefedve, alacsony lángon 18 percig pároljuk, amíg a rizs megszívja a vizet.',
                '1 csokor apróra vágott petrezselyemmel megszórva tálaljuk.',
            ],
            93 => [ // Tojásos nokedli
                '800 g friss nokedlit bő vízben 2 percig főzünk, leszűrünk és lecsepegtetünk.',
                '6 db tojást felverünk, és 1 teáskanál sóval ízesítjük.',
                '2 evőkanál olajat serpenyőben felforrósítunk, beletesszük a nokedlit, és 3 percig pirítjuk.',
                'Ráöntjük a felvert tojást, és folyamatosan kevergetjük.',
                'Addig sütjük, amíg a tojás megszilárdul, de még szaftos marad.',
                '200 g tejföllel és 1 fej salátával tálaljuk.',
            ],
            94 => [ // Sajtos pogácsa
                '20 g élesztőt 150 ml langyos tejben 5 g cukorral felfuttatunk.',
                '500 g lisztet 200 g vajjal elmorzsolunk, és hozzáadunk 150 g tejfölt, 1 db tojást, 2 teáskanál sót és a felfutott élesztőt.',
                'Belegyúrunk 100 g reszelt sajtot, és sima tésztává dagasztjuk.',
                'Letakarva 1 órán át kelesztjük.',
                '2 cm vastagra nyújtjuk, kiszaggatjuk, tepsire rakjuk, megkenjük 1 db felvert tojással, és megszórjuk 100 g reszelt sajttal.',
                'Előmelegített sütőben 200°C-on 20 percig aranybarnára sütjük.',
            ],
            95 => [ // Csirke curry
                '600 g csirkemellet 2 cm-es kockákra vágunk.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, és hozzáadunk 2 gerezd zúzott fokhagymát és 15 g reszelt gyömbért.',
                'Megszórjuk 2 evőkanál curry porral, hozzáadjuk a csirkét, és 5 percig pirítjuk.',
                'Hozzáadunk 2 db felkockázott paradicsomot, felöntjük 200 ml tejszínnel, és 1 teáskanál sóval ízesítjük.',
                'Lefedve, lassú tűzön 15 percig pároljuk.',
                '300 g rizst 600 ml vízben megpárolunk, és a curryvel tálaljuk.',
            ],
            96 => [ // Meggyleves
                '500 g meggyet megmosunk és kimagozunk.',
                '1000 ml vizet 120 g cukorral és 0,5 teáskanál fahéjjal felforralunk, beletesszük a meggyet, és 10 percig főzzük.',
                '1 evőkanál keményítőt 200 ml tejszínnel simára keverünk, a levesbe öntjük, és összeforraljuk.',
                'Lehűtjük, és legalább 2 órára hűtőbe téve hidegen tálaljuk.',
            ],
            97 => [ // Sajtos makaróni
                '400 g makarónit bő vízben kifőzünk, és leszűrünk.',
                '40 g vajat felolvasztunk, 30 g lisztet 1 percig pirítunk benne, majd 500 ml tejjel csomómentesre keverjük.',
                'Belekeverünk 200 g reszelt sajtot, és 1 teáskanál sóval, 0,25 teáskanál borssal ízesítjük.',
                'A makarónit összekeverjük a sajtos szósszal, és tepsibe öntjük.',
                'Megszórjuk 50 g reszelt sajttal, és előmelegített sütőben 200°C-on 20 percig aranybarnára sütjük.',
            ],
            98 => [ // Hagymás rostélyos
                '800 g marharostélyost 4 szeletre vágunk, kiklopfolunk, 1 teáskanál sóval és 0,5 teáskanál borssal fűszerezünk, és 30 g lisztbe forgatjuk.',
                '3 db hagymát vékony karikákra vágunk.',
                '2 evőkanál olajon a húsokat oldalanként 3 percig sütjük, majd felöntjük 200 ml vízzel, és fedő alatt 40 percig pároljuk.',
                'Közben 2 evőkanál olajon a hagymakarikákat aranybarnára pirítjuk.',
                '800 g burgonyát meghámozunk, felkockázunk, és puhára főzzük.',
                'A húst a pirított hagymával a tetején, a burgonyával tálaljuk.',
            ],
            99 => [ // Epres tiramisu
                '4 db tojás sárgáját 100 g cukorral habosra keverjük, és hozzáadunk 500 g mascarponét.',
                'A 4 tojás fehérjét kemény habbá verjük, és óvatosan a mascarponés krémbe forgatjuk.',
                '300 ml kávét lefőzünk és kihűtünk; 400 g epret felszeletelünk.',
                '300 g babapiskóta felét egyenként a kávéba mártjuk, és egy tál aljára fektetjük, majd rákenjük a krém felét, és rászórjuk az eper felét.',
                'A maradék piskótával, krémmel és eperrel megismételjük a rétegezést.',
                'Hűtőben legalább 4 órát pihentetjük, és 20 g kakaóporral megszórva tálaljuk.',
            ],
            100 => [ // Zöldséges omlett
                '4 db tojást felverünk, és 0,5 teáskanál sóval, 0,25 teáskanál borssal ízesítjük.',
                '1 db paprikát és 1 db paradicsomot megmosunk és felkockázunk.',
                '1 evőkanál olajat serpenyőben felforrósítunk, és a zöldségeket 3 percig pirítjuk.',
                'Ráöntjük a felvert tojást, és megszórjuk 50 g reszelt sajttal.',
                'Amikor a tojás alja megszilárdult, az omlettet félbehajtjuk.',
                'Mindkét oldalát aranybarnára sütjük, és melegen tálaljuk.',
            ],
            101 => [ // Hortobágyi palacsinta
                '200 g lisztből, 2 db tojásból, 400 ml tejből és 0,25 teáskanál sóból palacsintatésztát keverünk, és 2 evőkanál olajjal 12 vékony palacsintát sütünk.',
                '500 g csirkemellet megmosunk és apró kockákra vágunk.',
                '1 db hagymát apróra vágunk, 2 evőkanál olajon megdinszteljük, megszórjuk 1 evőkanál pirospaprika őrleménnyel, és hozzáadjuk a csirkét.',
                'Hozzáadunk 1 db felszeletelt paprikát és 1 db paradicsomot, 1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, felöntjük 200 ml vízzel, és 20 percig pároljuk.',
                'A húst szűrőkanállal kiszedjük, finomra vágjuk, a palacsintákat megtöltjük vele, és a széleket behajtva tepsibe fektetjük.',
                'A visszamaradt szaftot 300 g tejföllel és 20 g liszttel behabarjuk, a palacsintákra öntjük, és 180°C-on 15 percig sütjük.',
            ],
            102 => [ // Újházy-tyúkhúsleves
                '1500 g tyúkhúst 3000 ml hideg vízben feltesszük főni, és felforrás után a habot gondosan leszedjük.',
                '2 teáskanál sóval, 1 teáskanál egész borssal és 2 db babérlevéllel ízesítjük, és lassú tűzön 2 órán át gyöngyözve főzzük.',
                'Hozzáadunk 3 db megtisztított sárgarépát, 1 db zellert és 1 db egész hagymát, és további 40 percig főzzük.',
                '200 g gombát felszeletelünk, és 100 g zöldborsóval együtt az utolsó 15 percben a leveshez adjuk.',
                '200 g csigatésztát külön kifőzünk, és leszűrünk.',
                'A húst lecsontozzuk, feldaraboljuk, és a zöldségekkel, a gombával és a csigatésztával együtt a levesben tálaljuk.',
            ],
            103 => [ // Brassói aprópecsenye
                '600 g sertéshúst ujjnyi csíkokra vágunk, és 1 teáskanál sóval, 0,5 teáskanál borssal fűszerezzük.',
                '800 g burgonyát meghámozunk, 1 cm-es kockákra vágunk, 3 evőkanál olajon gyakran forgatva ropogósra sütjük, és 0,5 teáskanál sóval megszórjuk.',
                '2 evőkanál olajon a húst magas lángon 5 percig pirítjuk.',
                'Hozzáadunk 4 gerezd zúzott fokhagymát és 1 evőkanál pirospaprika őrleményt, és felöntjük 100 ml vízzel.',
                'Fedő alatt 20 percig pároljuk, amíg a hús megpuhul.',
                'A sült burgonyát a húshoz forgatjuk, és azonnal tálaljuk.',
            ],
            104 => [ // Somlói galuska
                '6 db tojást 150 g cukorral habosra verünk, beleforgatunk 150 g lisztet, majd a masszát három egyenlő részre osztjuk: az elsőbe 20 g kakaóport, a másodikba 50 g darált diót keverünk, a harmadik natúr (sima) piskóta marad.',
                'A három piskótát külön-külön 180°C-on 15 perc alatt kisütjük, kihűtjük, és kockákra vágjuk.',
                'Vaníliasodót készítünk: 500 ml tejet 1 teáskanál vaníliával felforralunk, 4 db tojássárgáját 100 g cukorral kikeverünk, és a tejjel együtt sűrűre főzzük.',
                '100 g csokoládét 100 ml tejszínnel vízgőz felett simára olvasztunk.',
                'A piskótakockákat tálba rétegezzük, és meglocsoljuk a vaníliasodóval.',
                '200 ml tejszínt habbá verünk, és a galuskákat csokoládéöntettel, tejszínhabbal és 30 g durvára vágott dióval tálaljuk.',
            ],
            105 => [ // Debreceni gulyás
                '2 db hagymát apróra vágunk, és 3 evőkanál olajon megdinszteljük.',
                'Levesszük a tűzről, belekeverünk 2 evőkanál pirospaprika őrleményt, és felöntjük 2000 ml vízzel.',
                'Hozzáadunk 800 g felkockázott burgonyát és 2 db karikára vágott sárgarépát, és 1,5 teáskanál sóval, 0,5 teáskanál borssal ízesítjük.',
                '400 g debreceni kolbászt felkarikázunk, és a leveshez adjuk.',
                'Hozzáadunk 2 db felszeletelt paprikát és 1 db paradicsomot.',
                'Lassú tűzön 30 percig főzzük, és forrón tálaljuk.',
            ],
            106 => [ // Garnélás pad thai
                '250 g rizstésztát 10 percre langyos vízbe áztatunk, majd leszűrjük.',
                'A szószhoz 3 evőkanál szójaszószt, 20 g cukrot, 1 db citrom levét és 0,5 teáskanál chilit összekeverünk.',
                'Wokban 3 evőkanál olajat forrósítunk, és 2 gerezd zúzott fokhagymán 300 g megtisztított garnélát 2 percig pirítunk.',
                'A garnélát a wok szélére toljuk, mellé ütünk 2 db tojást, és kevergetve megsütjük.',
                'Hozzáadjuk a tésztát és a szószt, és 3 percig forgatva pirítjuk.',
                '1 db felkarikázott újhagymával és 50 g durvára vágott, pirított földimogyoróval megszórva tálaljuk.',
            ],
            107 => [ // Teriyaki lazac szezámmaggal
                '300 g rizst 600 ml vízben megpárolunk.',
                'A teriyaki szószhoz 4 evőkanál szójaszószt, 2 evőkanál mézet, 10 g reszelt gyömbért, 2 gerezd zúzott fokhagymát és 1 evőkanál keményítőt 50 ml vízzel simára keverünk.',
                '600 g lazacfilét 4 szeletre vágunk, és 1 evőkanál olajon a bőrös oldalával lefelé 4 percig sütjük, majd megfordítjuk.',
                'Ráöntjük a teriyaki szószt, és 3 percig forgatva sűrűre főzzük, amíg bevonja a halat.',
                '400 g brokkolit rózsáira szedünk, és forrásban lévő vízben 4 percig főzzük.',
                'A lazacot a rizzsel és a brokkolival tálaljuk, 15 g pirított szezámmaggal megszórva.',
            ],
            108 => [ // Szezámos-mogyorós tofu tál
                '300 g rizst 600 ml vízben megpárolunk.',
                '400 g tofut lecsöpögtetünk, 2 cm-es kockákra vágunk, és 2 evőkanál keményítőbe forgatjuk.',
                '2 evőkanál olajon a tofut minden oldalán ropogósra sütjük, majd kiszedjük.',
                '1 evőkanál olajon 300 g brokkolirózsát és 2 db csíkokra vágott sárgarépát 2 gerezd zúzott fokhagymával és 10 g reszelt gyömbérrel 5 percig pirítunk.',
                'Visszatesszük a tofut, 4 evőkanál szójaszósszal és 10 g cukorral ízesítjük, és átforgatjuk.',
                'A rizzsel tálaljuk, 40 g pirított földimogyoróval és 15 g szezámmaggal megszórva.',
            ],
            109 => [ // Mustáros-mézes lazac
                '600 g lazacfilét 4 szeletre vágunk, és 1 teáskanál sóval, 0,5 teáskanál borssal fűszerezzük.',
                'A mázhoz 2 evőkanál mustárt, 2 evőkanál mézet, 1 gerezd zúzott fokhagymát és 0,5 db citrom levét összekeverünk.',
                'A halat sütőpapírral bélelt tepsibe fektetjük, és megkenjük a mustáros mázzal.',
                'Előmelegített sütőben 200°C-on 15 percig sütjük.',
                '1 fej salátát megmosunk, falatnyira tépkedünk, és 1 evőkanál olajjal és a maradék 0,5 db citrom levével meglocsoljuk.',
                'A lazacot a salátával tálaljuk.',
            ],
            110 => [ // Fokhagymás garnélás spagetti
                '400 g spagettit bő vízben kifőzünk, és leszűrünk.',
                '4 evőkanál olajon 4 gerezd vékonyra szeletelt fokhagymát és 0,5 teáskanál chilit alacsony lángon 2 percig pirítunk.',
                'Hozzáadunk 400 g megtisztított garnélát, 1 teáskanál sóval és 0,25 teáskanál borssal ízesítjük, és oldalanként 1-2 percig sütjük.',
                'Belekeverünk 20 g vajat és 1 db citrom levét.',
                'Hozzáforgatjuk a leszűrt spagettit.',
                '1 csokor apróra vágott petrezselyemmel megszórva tálaljuk.',
            ],
            111 => [ // Tzatziki
                '1 db uborkát lereszelünk, megszórjuk 0,5 teáskanál sóval, és 10 perc után alaposan kinyomkodjuk.',
                '400 g sűrű joghurtot összekeverünk az uborkával és 2 gerezd zúzott fokhagymával.',
                '0,5 db citrom levével és 0,25 teáskanál borssal ízesítjük.',
                'Tálba simítjuk, és meglocsoljuk 1 evőkanál olívaolajjal.',
                '30 percig hűtőben pihentetjük, majd 2 db csíkokra vágott paprikával tálaljuk.',
            ],
            112 => [ // Házi limonádé
                '100 g cukrot 200 ml meleg vízben feloldunk, és kihűtjük.',
                '3 db citromot kifacsarunk, és a levét a cukorsziruphoz adjuk.',
                'Felöntjük 800 ml hideg vízzel, és elkeverjük.',
                'A maradék 1 db citromot vékony karikákra vágjuk, és a limonádéba tesszük.',
                'Legalább 1 órára hűtőbe tesszük, és jól lehűtve tálaljuk.',
            ],
            113 => [ // Epres-banános smoothie
                '200 g epret megmosunk és megcsumázunk, 1 db banánt meghámozunk és felkarikázunk.',
                'A gyümölcsöket turmixgépbe tesszük 200 g joghurttal és 200 ml hideg tejjel.',
                'Hozzáadunk 1 evőkanál mézet és 30 g zabpelyhet.',
                'Simára turmixoljuk, és 2 pohárba töltve azonnal tálaljuk.',
            ],
            114 => [ // Mézes-gyömbéres citromos tea
                '30 g gyömbért meghámozunk és vékonyra szeletelünk.',
                '1000 ml vizet a gyömbérrel és 0,5 teáskanál fahéjjal felforralunk, majd alacsony lángon 10 percig főzzük.',
                'Leszűrjük, és langyosra hűlni hagyjuk.',
                'Belekeverjük 1 db citrom levét és 4 evőkanál mézet (a mézet csak langyos teába tesszük, hogy megőrizze értékes anyagait).',
                'Bögrékbe töltve, melegen tálaljuk.',
            ],
            115 => [ // Meggybefőtt
                '2000 g meggyet megmosunk, a szárát eltávolítjuk (kimagozni nem kötelező).',
                '6 db fél literes befőttesüveget és a tetejüket forró vízzel kimossuk, és 100°C-os sütőben 10 percig sterilizáljuk.',
                'A meggyet szorosan az üvegekbe rétegezzük.',
                '1000 ml vizet 400 g cukorral felforralunk, és a forró sziruppal az üvegeket színültig töltjük.',
                'Lezárjuk, és egy nagy lábasban, vízfürdőben 15 percig 85°C-on dunsztoljuk.',
                'Az üvegeket pokróc alá téve 1 napig lassan hűlni hagyjuk, majd hűvös, sötét helyen tároljuk.',
            ],
            116 => [ // Almabefőtt fahéjjal
                '10 db almát meghámozunk, kimagozunk, és gerezdekre vágunk.',
                '1 db citrom levét az almára csorgatjuk, hogy ne barnuljon meg.',
                '6 db fél literes befőttesüveget és a tetejüket forró vízzel kimossuk, és 100°C-os sütőben 10 percig sterilizáljuk.',
                '1000 ml vizet 300 g cukorral és 1 teáskanál fahéjjal felforralunk, beletesszük az almát, és 3 percig főzzük.',
                'Az almát az üvegekbe szedjük, felöntjük a forró sziruppal, és lezárjuk.',
                'Vízfürdőben 15 percig dunsztoljuk, majd pokróc alatt 1 napig hűlni hagyjuk.',
            ],
            117 => [ // Eperlekvár
                '1500 g epret megmosunk, megcsumázunk, és negyedekre vágunk.',
                'Egy széles lábasban összekeverjük 750 g cukorral, és 1 órán át állni hagyjuk, hogy levet engedjen.',
                'Hozzáadjuk 1 db citrom levét, és felforraljuk.',
                'Közepes lángon, kevergetve 25 perc alatt sűrűre főzzük, közben a habját leszedjük.',
                'Forrón 5 db kisebb, sterilizált befőttesüvegbe töltjük, és lezárjuk.',
                'Az üvegeket fejjel lefelé fordítva, letakarva hagyjuk kihűlni.',
            ],
            118 => [ // Gyümölcssaláta
                '2 db almát kimagozunk és felkockázunk, 2 db banánt felkarikázunk.',
                '200 g epret negyedelünk, 100 g málnát óvatosan megmosunk.',
                'A gyümölcsöket tálba tesszük, és 0,5 db citrom levével meglocsoljuk.',
                '2 evőkanál mézzel óvatosan összeforgatjuk.',
                '30 g durvára vágott dióval megszórva, hidegen tálaljuk.',
            ],
            119 => [ // Sült alma dióval
                '4 db almát megmosunk, és a magházukat almavájóval kiemeljük.',
                '60 g darált diót 2 evőkanál mézzel és 1 teáskanál fahéjjal összekeverünk.',
                'Az almák közepét megtöltjük a diós töltelékkel, és a tetejükre elosztunk 30 g vajat.',
                'Tepsibe állítjuk, és előmelegített sütőben 180°C-on 25 percig sütjük.',
                '1 evőkanál mézzel meglocsolva, melegen tálaljuk.',
            ],
            120 => [ // Csokoládés eper
                '400 g epret megmosunk, és papírtörlőn teljesen szárazra törlünk (a zöld szárát rajta hagyjuk).',
                '150 g csokoládét vízgőz felett megolvasztunk.',
                'Az epreket a száruknál fogva kétharmadig a csokoládéba mártjuk.',
                'A csokis részt 30 g darált dióba mártjuk, és sütőpapírra fektetjük.',
                '20 percre hűtőbe tesszük, amíg a csokoládé megdermed, majd tálaljuk.',
            ],
            121 => [ // Garnélás sült rizs
                '300 g rizst előző nap 600 ml vízben megpárolunk, és hűtőben tároljuk (a hideg rizs nem ragad össze sütéskor).',
                'Wokban 1 evőkanál olajon 3 db felvert tojást rántottává sütünk, majd kiszedjük.',
                '1 evőkanál olajon 300 g megtisztított garnélát 2 percig sütünk, majd kiszedjük.',
                '1 evőkanál olajon 1 db apróra vágott hagymát, 2 gerezd zúzott fokhagymát, 1 db felkockázott sárgarépát és 150 g zöldborsót 3 percig pirítunk.',
                'Hozzáadjuk a hideg rizst, magas lángon 3 percig pirítjuk, majd 3 evőkanál szójaszósszal ízesítjük.',
                'Visszatesszük a tojást és a garnélát, átforgatjuk, és 10 g pirított szezámmaggal megszórva tálaljuk.',
            ],
        ];

        $records = [];
        foreach ($recipeSteps as $recipeId => $steps) {
            foreach ($steps as $order => $description) {
                $records[] = [
                    'description' => $description,
                    'recipe_id' => $recipeId,
                    'step_category_id' => $this->guessCategoryId($description),
                    'order' => $order + 1,
                ];
            }
        }

        foreach (array_chunk($records, 100) as $chunk) {
            DB::table('step')->insert($chunk);
        }
    }

    private function guessCategoryId(string $description): ?int
    {
        $categories = DB::table('step_category')->pluck('id', 'name');
        $d = mb_strtolower($description, 'UTF-8');

        if (preg_match('/tálal|tányér|köret/u', $d)) {
            return $categories['Tálalás'] ?? null;
        }
        if (preg_match('/sütő|tepsi|°C/u', $d)) {
            return $categories['Sütés'] ?? null;
        }
        if (preg_match('/főz|forral|párol|pirít|dinsztel|lassú tűz|felöntjük|habará|serpenyő|sütjük/u', $d)) {
            return $categories['Főzés'] ?? null;
        }
        if (preg_match('/megmos|vág|apró|kocká|hámoz|tisztít|szeletel|darabol|aprít|felfuttat|szitál|dagaszt|keleszt|nyújt|felver/u', $d)) {
            return $categories['Előkészítés'] ?? null;
        }

        return $categories['Elkészítés'] ?? null;
    }
}
